//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbs_Log
    /// </summary>
    [Serializable()]
    [AttributeTable("tbs_Log")]
    public class Entity_Log : Framework.Data.OM.Entity
    {
        
        private int _logID;
        
        /// <summary>
        /// logID
        /// </summary>
        public static string M_logID = "logID";
        
        private string _create_user;
        
        /// <summary>
        /// create_user
        /// </summary>
        public static string M_create_user = "create_user";
        
        private string _create_dt;
        
        /// <summary>
        /// create_dt
        /// </summary>
        public static string M_create_dt = "create_dt";
        
        private string _Operation_Name;
        
        /// <summary>
        /// Operation_Name
        /// </summary>
        public static string M_Operation_Name = "Operation_Name";
        
        private string _type_flg;
        
        /// <summary>
        /// type_flg
        /// </summary>
        public static string M_type_flg = "type_flg";
        
        /// <summary>
        /// logID
        /// </summary>
        [AttributeField("logID", "System.Int32", false, true, true, "Int32")]
        public int logID
        {
            get
            {
                return this._logID;
            }
            set
            {
                this._logID = value;
            }
        }
        
        /// <summary>
        /// create_user
        /// </summary>
        [AttributeField("create_user", "System.String", false, false, false, "String")]
        public string create_user
        {
            get
            {
                return this._create_user;
            }
            set
            {
                this._create_user = value;
            }
        }
        
        /// <summary>
        /// create_dt
        /// </summary>
        [AttributeField("create_dt", "System.String", false, false, false, "String")]
        public string create_dt
        {
            get
            {
                return this._create_dt;
            }
            set
            {
                this._create_dt = value;
            }
        }
        
        /// <summary>
        /// Operation_Name
        /// </summary>
        [AttributeField("Operation_Name", "System.String", false, false, false, "String")]
        public string Operation_Name
        {
            get
            {
                return this._Operation_Name;
            }
            set
            {
                this._Operation_Name = value;
            }
        }
        
        /// <summary>
        /// type_flg
        /// </summary>
        [AttributeField("type_flg", "System.String", false, false, false, "String")]
        public string type_flg
        {
            get
            {
                return this._type_flg;
            }
            set
            {
                this._type_flg = value;
            }
        }
    }
    
    /// <summary>
    /// tbs_Log
    /// </summary>
    [Serializable()]
    public class Entity_LogSet : EntitySet<Entity_Log>
    {
    }
}
