//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------
//*  修改記錄：2020/12/30  陳永銘

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_Card_BaseInfo
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_Card_BaseInfo")]
    public class Entity_CardBaseInfo : Framework.Data.OM.Entity
    {
        
        private string _indate1;
        
        /// <summary>
        /// indate1
        /// </summary>
        public static string M_indate1 = "indate1";
        
        private string _action;
        
        /// <summary>
        /// action
        /// </summary>
        public static string M_action = "action";
        
        private string _kind;
        
        /// <summary>
        /// kind
        /// </summary>
        public static string M_kind = "kind";
        
        private string _cardtype;
        
        /// <summary>
        /// cardtype
        /// </summary>
        public static string M_cardtype = "cardtype";
        
        private string _photo;
        
        /// <summary>
        /// photo
        /// </summary>
        public static string M_photo = "photo";
        
        private string _affinity;
        
        /// <summary>
        /// affinity
        /// </summary>
        public static string M_affinity = "affinity";
        
        private string _id;
        
        /// <summary>
        /// id
        /// </summary>
        public static string M_id = "id";
        
        private string _cardno;
        
        /// <summary>
        /// cardno
        /// </summary>
        public static string M_cardno = "cardno";
        
        private string _cardno2;
        
        /// <summary>
        /// cardno2
        /// </summary>
        public static string M_cardno2 = "cardno2";
        
        private string _zip;
        
        /// <summary>
        /// zip
        /// </summary>
        public static string M_zip = "zip";
        
        private string _add1;
        
        /// <summary>
        /// add1
        /// </summary>
        public static string M_add1 = "add1";
        
        private string _add2;
        
        /// <summary>
        /// add2
        /// </summary>
        public static string M_add2 = "add2";
        
        private string _add3;
        
        /// <summary>
        /// add3
        /// </summary>
        public static string M_add3 = "add3";
        
        private string _mailno;
        
        /// <summary>
        /// mailno
        /// </summary>
        public static string M_mailno = "mailno";
        
        private System.Nullable<int> _n_card;
        
        /// <summary>
        /// n_card
        /// </summary>
        public static string M_n_card = "n_card";
        
        private string _maildate;
        
        /// <summary>
        /// maildate
        /// </summary>
        public static string M_maildate = "maildate";
        
        private string _expdate;
        
        /// <summary>
        /// expdate
        /// </summary>
        public static string M_expdate = "expdate";
        
        private string _expdate2;
        
        /// <summary>
        /// expdate2
        /// </summary>
        public static string M_expdate2 = "expdate2";
        
        private string _seq;
        
        /// <summary>
        /// seq
        /// </summary>
        public static string M_seq = "seq";
        
        private string _custname;
        
        /// <summary>
        /// custname
        /// </summary>
        public static string M_custname = "custname";
        
        private string _name1;
        
        /// <summary>
        /// name1
        /// </summary>
        public static string M_name1 = "name1";
        
        private string _name2;
        
        /// <summary>
        /// name2
        /// </summary>
        public static string M_name2 = "name2";
        
        private string _trandate;
        
        /// <summary>
        /// trandate
        /// </summary>
        public static string M_trandate = "trandate";
        
        private string _card_file;
        
        /// <summary>
        /// card_file
        /// </summary>
        public static string M_card_file = "card_file";
        
        private string _disney_code;
        
        /// <summary>
        /// disney_code
        /// </summary>
        public static string M_disney_code = "disney_code";
        
        private string _branch_id;
        
        /// <summary>
        /// branch_id
        /// </summary>
        public static string M_branch_id = "branch_id";
        
        private string _Merch_Code;
        
        /// <summary>
        /// Merch_Code
        /// </summary>
        public static string M_Merch_Code = "Merch_Code";
        
        private string _monlimit;
        
        /// <summary>
        /// monlimit
        /// </summary>
        public static string M_monlimit = "monlimit";
        
        private string _is_LackCard;
        
        /// <summary>
        /// is_LackCard
        /// </summary>
        public static string M_is_LackCard = "is_LackCard";
        
        private string _Urgency_Flg;
        
        /// <summary>
        /// Urgency_Flg
        /// </summary>
        public static string M_Urgency_Flg = "Urgency_Flg";
        
        private string _IntoStore_Status;
        
        /// <summary>
        /// IntoStore_Status
        /// </summary>
        public static string M_IntoStore_Status = "IntoStore_Status";
        
        private string _IntoStore_Date;
        
        /// <summary>
        /// IntoStore_Date
        /// </summary>
        public static string M_IntoStore_Date = "IntoStore_Date";
        
        private string _OutStore_Status;
        
        /// <summary>
        /// OutStore_Status
        /// </summary>
        public static string M_OutStore_Status = "OutStore_Status";
        
        private string _OutStore_Date;
        
        /// <summary>
        /// OutStore_Date
        /// </summary>
        public static string M_OutStore_Date = "OutStore_Date";
        
        private string _SelfPick_Type;
        
        /// <summary>
        /// SelfPick_Type
        /// </summary>
        public static string M_SelfPick_Type = "SelfPick_Type";
        
        private string _SelfPick_Date;
        
        /// <summary>
        /// SelfPick_Date
        /// </summary>
        public static string M_SelfPick_Date = "SelfPick_Date";
        
        private string _OriginalDBflg;
        /// <summary>
        /// OriginalDBflg
        /// </summary>
        public static string M_OriginalDBflg = "OriginalDBflg";
        /// <summary>
        /// indate1
        /// </summary>
        [AttributeField("indate1", "System.String", false, false, false, "String")]
        public string indate1
        {
            get
            {
                return this._indate1;
            }
            set
            {
                this._indate1 = value;
            }
        }
        
        /// <summary>
        /// action
        /// </summary>
        [AttributeField("action", "System.String", false,true, false, "String")]
        public string action
        {
            get
            {
                return this._action;
            }
            set
            {
                this._action = value;
            }
        }
        
        /// <summary>
        /// kind
        /// </summary>
        [AttributeField("kind", "System.String", false, false, false, "String")]
        public string kind
        {
            get
            {
                return this._kind;
            }
            set
            {
                this._kind = value;
            }
        }
        
        /// <summary>
        /// cardtype
        /// </summary>
        [AttributeField("cardtype", "System.String", false, false, false, "String")]
        public string cardtype
        {
            get
            {
                return this._cardtype;
            }
            set
            {
                this._cardtype = value;
            }
        }
        
        /// <summary>
        /// photo
        /// </summary>
        [AttributeField("photo", "System.String", false, false, false, "String")]
        public string photo
        {
            get
            {
                return this._photo;
            }
            set
            {
                this._photo = value;
            }
        }
        
        /// <summary>
        /// affinity
        /// </summary>
        [AttributeField("affinity", "System.String", false, false, false, "String")]
        public string affinity
        {
            get
            {
                return this._affinity;
            }
            set
            {
                this._affinity = value;
            }
        }
        
        /// <summary>
        /// id
        /// </summary>
        [AttributeField("id", "System.String", false, true, false, "String")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }
        
        /// <summary>
        /// cardno
        /// </summary>
        [AttributeField("cardno", "System.String", false, true, false, "String")]
        public string cardno
        {
            get
            {
                return this._cardno;
            }
            set
            {
                this._cardno = value;
            }
        }
        
        /// <summary>
        /// cardno2
        /// </summary>
        [AttributeField("cardno2", "System.String", false, false, false, "String")]
        public string cardno2
        {
            get
            {
                return this._cardno2;
            }
            set
            {
                this._cardno2 = value;
            }
        }
        
        /// <summary>
        /// zip
        /// </summary>
        [AttributeField("zip", "System.String", false, false, false, "String")]
        public string zip
        {
            get
            {
                return this._zip;
            }
            set
            {
                this._zip = value;
            }
        }
        
        /// <summary>
        /// add1
        /// </summary>
        [AttributeField("add1", "System.String", false, false, false, "String")]
        public string add1
        {
            get
            {
                return this._add1;
            }
            set
            {
                this._add1 = value;
            }
        }
        
        /// <summary>
        /// add2
        /// </summary>
        [AttributeField("add2", "System.String", false, false, false, "String")]
        public string add2
        {
            get
            {
                return this._add2;
            }
            set
            {
                this._add2 = value;
            }
        }
        
        /// <summary>
        /// add3
        /// </summary>
        [AttributeField("add3", "System.String", false, false, false, "String")]
        public string add3
        {
            get
            {
                return this._add3;
            }
            set
            {
                this._add3 = value;
            }
        }
        
        /// <summary>
        /// mailno
        /// </summary>
        [AttributeField("mailno", "System.String", false, false, false, "String")]
        public string mailno
        {
            get
            {
                return this._mailno;
            }
            set
            {
                this._mailno = value;
            }
        }
        
        /// <summary>
        /// n_card
        /// </summary>
        [AttributeField("n_card", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> n_card
        {
            get
            {
                return this._n_card;
            }
            set
            {
                this._n_card = value;
            }
        }
        
        /// <summary>
        /// maildate
        /// </summary>
        [AttributeField("maildate", "System.String", false, false, false, "String")]
        public string maildate
        {
            get
            {
                return this._maildate;
            }
            set
            {
                this._maildate = value;
            }
        }
        
        /// <summary>
        /// expdate
        /// </summary>
        [AttributeField("expdate", "System.String", false, false, false, "String")]
        public string expdate
        {
            get
            {
                return this._expdate;
            }
            set
            {
                this._expdate = value;
            }
        }
        
        /// <summary>
        /// expdate2
        /// </summary>
        [AttributeField("expdate2", "System.String", false, false, false, "String")]
        public string expdate2
        {
            get
            {
                return this._expdate2;
            }
            set
            {
                this._expdate2 = value;
            }
        }
        
        /// <summary>
        /// seq
        /// </summary>
        [AttributeField("seq", "System.String", false, false, false, "String")]
        public string seq
        {
            get
            {
                return this._seq;
            }
            set
            {
                this._seq = value;
            }
        }
        
        /// <summary>
        /// custname
        /// </summary>
        [AttributeField("custname", "System.String", false, false, false, "String")]
        public string custname
        {
            get
            {
                return this._custname;
            }
            set
            {
                this._custname = value;
            }
        }
        
        /// <summary>
        /// name1
        /// </summary>
        [AttributeField("name1", "System.String", false, false, false, "String")]
        public string name1
        {
            get
            {
                return this._name1;
            }
            set
            {
                this._name1 = value;
            }
        }
        
        /// <summary>
        /// name2
        /// </summary>
        [AttributeField("name2", "System.String", false, false, false, "String")]
        public string name2
        {
            get
            {
                return this._name2;
            }
            set
            {
                this._name2 = value;
            }
        }
        
        /// <summary>
        /// trandate
        /// </summary>
        [AttributeField("trandate", "System.String", false, true, false, "String")]
        public string trandate
        {
            get
            {
                return this._trandate;
            }
            set
            {
                this._trandate = value;
            }
        }
        
        /// <summary>
        /// card_file
        /// </summary>
        [AttributeField("card_file", "System.String", false, false, false, "String")]
        public string card_file
        {
            get
            {
                return this._card_file;
            }
            set
            {
                this._card_file = value;
            }
        }
        
        /// <summary>
        /// disney_code
        /// </summary>
        [AttributeField("disney_code", "System.String", false, false, false, "String")]
        public string disney_code
        {
            get
            {
                return this._disney_code;
            }
            set
            {
                this._disney_code = value;
            }
        }
        
        /// <summary>
        /// branch_id
        /// </summary>
        [AttributeField("branch_id", "System.String", false, false, false, "String")]
        public string branch_id
        {
            get
            {
                return this._branch_id;
            }
            set
            {
                this._branch_id = value;
            }
        }
        
        /// <summary>
        /// Merch_Code
        /// </summary>
        [AttributeField("Merch_Code", "System.String", false, false, false, "String")]
        public string Merch_Code
        {
            get
            {
                return this._Merch_Code;
            }
            set
            {
                this._Merch_Code = value;
            }
        }
        
        /// <summary>
        /// monlimit
        /// </summary>
        [AttributeField("monlimit", "System.String", false, false, false, "String")]
        public string monlimit
        {
            get
            {
                return this._monlimit;
            }
            set
            {
                this._monlimit = value;
            }
        }
        
        /// <summary>
        /// is_LackCard
        /// </summary>
        [AttributeField("is_LackCard", "System.String", false, false, false, "String")]
        public string is_LackCard
        {
            get
            {
                return this._is_LackCard;
            }
            set
            {
                this._is_LackCard = value;
            }
        }
        
        /// <summary>
        /// Urgency_Flg
        /// </summary>
        [AttributeField("Urgency_Flg", "System.String", false, false, false, "String")]
        public string Urgency_Flg
        {
            get
            {
                return this._Urgency_Flg;
            }
            set
            {
                this._Urgency_Flg = value;
            }
        }
        
        /// <summary>
        /// IntoStore_Status
        /// </summary>
        [AttributeField("IntoStore_Status", "System.String", false, false, false, "String")]
        public string IntoStore_Status
        {
            get
            {
                return this._IntoStore_Status;
            }
            set
            {
                this._IntoStore_Status = value;
            }
        }
        
        /// <summary>
        /// IntoStore_Date
        /// </summary>
        [AttributeField("IntoStore_Date", "System.String", false, false, false, "String")]
        public string IntoStore_Date
        {
            get
            {
                return this._IntoStore_Date;
            }
            set
            {
                this._IntoStore_Date = value;
            }
        }
        
        /// <summary>
        /// OutStore_Status
        /// </summary>
        [AttributeField("OutStore_Status", "System.String", false, false, false, "String")]
        public string OutStore_Status
        {
            get
            {
                return this._OutStore_Status;
            }
            set
            {
                this._OutStore_Status = value;
            }
        }
        
        /// <summary>
        /// OutStore_Date
        /// </summary>
        [AttributeField("OutStore_Date", "System.String", false, false, false, "String")]
        public string OutStore_Date
        {
            get
            {
                return this._OutStore_Date;
            }
            set
            {
                this._OutStore_Date = value;
            }
        }
        
        /// <summary>
        /// SelfPick_Type
        /// </summary>
        [AttributeField("SelfPick_Type", "System.String", false, false, false, "String")]
        public string SelfPick_Type
        {
            get
            {
                return this._SelfPick_Type;
            }
            set
            {
                this._SelfPick_Type = value;
            }
        }
        
        /// <summary>
        /// SelfPick_Date
        /// </summary>
        [AttributeField("SelfPick_Date", "System.String", false, false, false, "String")]
        public string SelfPick_Date
        {
            get
            {
                return this._SelfPick_Date;
            }
            set
            {
                this._SelfPick_Date = value;
            }
        }
        /// <summary>
        /// OriginalDBflg
        /// </summary>
        [AttributeField("OriginalDBflg", "System.String", false, false, false, "String")]
        public string OriginalDBflg
        {
            get
            {
                return this._OriginalDBflg;
            }
            set
            {
                this._OriginalDBflg = value;
            }
        }

        // 2020/12/30  陳永銘 新增欄位:羅馬拼音 BEGIN
        // 歸戶姓名_羅馬拼音
        private string _custname_roma;
        public static string M_custname_roma = "custname_roma";
        /// <summary>
        /// custname_roma
        /// </summary>
        [AttributeField("custname_roma", "System.String", false, false, false, "String")]
        public string custname_roma
        {
            get
            {
                return this._custname_roma;
            }
            set
            {
                this._custname_roma = value;
            }
        }

        // 客戶姓名1_羅馬拼音
        private string _name1_roma;
        public static string M_name1_roma = "name1_roma";
        /// <summary>
        /// name1_roma
        /// </summary>
        [AttributeField("name1_roma", "System.String", false, false, false, "String")]
        public string name1_roma
        {
            get
            {
                return this._name1_roma;
            }
            set
            {
                this._name1_roma = value;
            }
        }
        // 2020/12/30  陳永銘 新增欄位:羅馬拼音 END                                         
    }

    /// <summary>
    /// tbl_Card_BaseInfo
    /// </summary>
    [Serializable()]
    public class Entity_CardBaseInfoSet : EntitySet<Entity_CardBaseInfo>
    {
    }
}
