//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_Card_DataChange
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_Card_DataChange")]
    public class Entity_CardDataChange : Framework.Data.OM.Entity
    {

        private int _Sno;

        /// <summary>
        /// Sno
        /// </summary>
        public static string M_Sno = "Sno";

        private string _ParentSno;

        /// <summary>
        /// ParentSno
        /// </summary>
        public static string M_ParentSno = "ParentSno";

        private string _indate1;

        /// <summary>
        /// indate1
        /// </summary>
        public static string M_indate1 = "indate1";

        private string _id;

        /// <summary>
        /// id
        /// </summary>
        public static string M_id = "id";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _action;

        /// <summary>
        /// action
        /// </summary>
        public static string M_action = "action";

        private string _Trandate;

        /// <summary>
        /// Trandate
        /// </summary>
        public static string M_Trandate = "Trandate";

        private string _OldName;

        /// <summary>
        /// OldName
        /// </summary>
        public static string M_OldName = "OldName";

        private string _NewName;

        /// <summary>
        /// NewName
        /// </summary>
        public static string M_NewName = "NewName";

        private string _OldMailDate;

        /// <summary>
        /// OldMailDate
        /// </summary>
        public static string M_OldMailDate = "OldMailDate";

        private string _NewMailDate;

        /// <summary>
        /// NewMailDate
        /// </summary>
        public static string M_NewMailDate = "NewMailDate";

        private System.Nullable<int> _OldMonlimit;

        /// <summary>
        /// OldMonlimit
        /// </summary>
        public static string M_OldMonlimit = "OldMonlimit";

        private System.Nullable<int> _NewMonlimit;

        /// <summary>
        /// NewMonlimit
        /// </summary>
        public static string M_NewMonlimit = "NewMonlimit";

        private string _OldWay;

        /// <summary>
        /// OldWay
        /// </summary>
        public static string M_OldWay = "OldWay";

        private string _NewWay;

        /// <summary>
        /// NewWay
        /// </summary>
        public static string M_NewWay = "NewWay";

        private string _OldSelfPickType;

        /// <summary>
        /// OldSelfPickType
        /// </summary>
        public static string M_OldSelfPickType = "OldSelfPickType";

        private string _NewSelfPickType;

        /// <summary>
        /// NewSelfPickType
        /// </summary>
        public static string M_NewSelfPickType = "NewSelfPickType";

        private string _enditem;

        /// <summary>
        /// enditem
        /// </summary>
        public static string M_enditem = "enditem";

        private string _newitem;

        /// <summary>
        /// newitem
        /// </summary>
        public static string M_newitem = "newitem";

        private string _oldMailno;

        /// <summary>
        /// oldMailno
        /// </summary>
        public static string M_oldMailno = "oldMailno";

        private string _newmailno;

        /// <summary>
        /// newmailno
        /// </summary>
        public static string M_newmailno = "newmailno";

        private string _OldZip;

        /// <summary>
        /// OldZip
        /// </summary>
        public static string M_OldZip = "OldZip";

        private string _OldAdd1;

        /// <summary>
        /// OldAdd1
        /// </summary>
        public static string M_OldAdd1 = "OldAdd1";

        private string _OldAdd2;

        /// <summary>
        /// OldAdd2
        /// </summary>
        public static string M_OldAdd2 = "OldAdd2";

        private string _OldAdd3;

        /// <summary>
        /// OldAdd3
        /// </summary>
        public static string M_OldAdd3 = "OldAdd3";

        private string _NewZip;

        /// <summary>
        /// NewZip
        /// </summary>
        public static string M_NewZip = "NewZip";

        private string _NewAdd1;

        /// <summary>
        /// NewAdd1
        /// </summary>
        public static string M_NewAdd1 = "NewAdd1";

        private string _NewAdd2;

        /// <summary>
        /// NewAdd2
        /// </summary>
        public static string M_NewAdd2 = "NewAdd2";

        private string _NewAdd3;

        /// <summary>
        /// NewAdd3
        /// </summary>
        public static string M_NewAdd3 = "NewAdd3";

        private string _CNote;

        /// <summary>
        /// CNote
        /// </summary>
        public static string M_CNote = "CNote";

        private string _photo;

        /// <summary>
        /// photo
        /// </summary>
        public static string M_photo = "photo";

        private string _UpdUser;

        /// <summary>
        /// UpdUser
        /// </summary>
        public static string M_UpdUser = "UpdUser";

        private string _UpdDate;

        /// <summary>
        /// UpdDate
        /// </summary>
        public static string M_UpdDate = "UpdDate";

        private string _UpdTime;

        /// <summary>
        /// UpdTime
        /// </summary>
        public static string M_UpdTime = "UpdTime";

        private string _UpMark;

        /// <summary>
        /// UpMark
        /// </summary>
        public static string M_UpMark = "UpMark";

        private string _NoteCaptions;

        /// <summary>
        /// NoteCaptions
        /// </summary>
        public static string M_NoteCaptions = "NoteCaptions";

        private string _CloseFlg;

        /// <summary>
        /// CloseFlg
        /// </summary>
        public static string M_CloseFlg = "CloseFlg";

        private string _MerchCode;

        /// <summary>
        /// MerchCode
        /// </summary>
        public static string M_MerchCode = "MerchCode";

        private string _UrgencyFlg;

        /// <summary>
        /// UrgencyFlg
        /// </summary>
        public static string M_UrgencyFlg = "UrgencyFlg";

        private string _OutputFlg;

        /// <summary>
        /// OutputFlg
        /// </summary>
        public static string M_OutputFlg = "OutputFlg";

        private string _OutputDate;

        /// <summary>
        /// OutputDate
        /// </summary>
        public static string M_OutputDate = "OutputDate";

        private string _OutputFileName;

        /// <summary>
        /// OutputFileName
        /// </summary>
        public static string M_OutputFileName = "OutputFileName";

        private string _SourceType;

        /// <summary>
        /// SourceType
        /// </summary>
        public static string M_SourceType = "SourceType";

        private string _BaseFlg;

        /// <summary>
        /// BaseFlg
        /// </summary>
        public static string M_BaseFlg = "BaseFlg";

        private string _Type_flg;

        /// <summary>
        /// Type_flg
        /// </summary>
        public static string M_Type_flg = "Type_flg";

        private string _FilePath;

        /// <summary>
        /// FilePath
        /// </summary>
        public static string M_FilePath = "FilePath";

        /// <summary>
        /// Sno
        /// </summary>
        [AttributeField("Sno", "System.Int32", false, false, true, "Int32")]
        public int Sno
        {
            get
            {
                return this._Sno;
            }
            set
            {
                this._Sno = value;
            }
        }

        /// <summary>
        /// ParentSno
        /// </summary>
        [AttributeField("ParentSno", "System.String", false, false, false, "String")]
        public string ParentSno
        {
            get
            {
                return this._ParentSno;
            }
            set
            {
                this._ParentSno = value;
            }
        }

        /// <summary>
        /// indate1
        /// </summary>
        [AttributeField("indate1", "System.String", false, false, false, "String")]
        public string indate1
        {
            get
            {
                return this._indate1;
            }
            set
            {
                this._indate1 = value;
            }
        }

        /// <summary>
        /// id
        /// </summary>
        [AttributeField("id", "System.String", false, true, false, "String")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, true, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// action
        /// </summary>
        [AttributeField("action", "System.String", false, true, false, "String")]
        public string action
        {
            get
            {
                return this._action;
            }
            set
            {
                this._action = value;
            }
        }

        /// <summary>
        /// Trandate
        /// </summary>
        [AttributeField("Trandate", "System.String", false, true, false, "String")]
        public string Trandate
        {
            get
            {
                return this._Trandate;
            }
            set
            {
                this._Trandate = value;
            }
        }

        /// <summary>
        /// OldName
        /// </summary>
        [AttributeField("OldName", "System.String", false, false, false, "String")]
        public string OldName
        {
            get
            {
                return this._OldName;
            }
            set
            {
                this._OldName = value;
            }
        }

        /// <summary>
        /// NewName
        /// </summary>
        [AttributeField("NewName", "System.String", false, false, false, "String")]
        public string NewName
        {
            get
            {
                return this._NewName;
            }
            set
            {
                this._NewName = value;
            }
        }

        /// <summary>
        /// OldMailDate
        /// </summary>
        [AttributeField("OldMailDate", "System.String", false, false, false, "String")]
        public string OldMailDate
        {
            get
            {
                return this._OldMailDate;
            }
            set
            {
                this._OldMailDate = value;
            }
        }

        /// <summary>
        /// NewMailDate
        /// </summary>
        [AttributeField("NewMailDate", "System.String", false, false, false, "String")]
        public string NewMailDate
        {
            get
            {
                return this._NewMailDate;
            }
            set
            {
                this._NewMailDate = value;
            }
        }

        /// <summary>
        /// OldMonlimit
        /// </summary>
        [AttributeField("OldMonlimit", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> OldMonlimit
        {
            get
            {
                return this._OldMonlimit;
            }
            set
            {
                this._OldMonlimit = value;
            }
        }

        /// <summary>
        /// NewMonlimit
        /// </summary>
        [AttributeField("NewMonlimit", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> NewMonlimit
        {
            get
            {
                return this._NewMonlimit;
            }
            set
            {
                this._NewMonlimit = value;
            }
        }

        /// <summary>
        /// OldWay
        /// </summary>
        [AttributeField("OldWay", "System.String", false, false, false, "String")]
        public string OldWay
        {
            get
            {
                return this._OldWay;
            }
            set
            {
                this._OldWay = value;
            }
        }

        /// <summary>
        /// NewWay
        /// </summary>
        [AttributeField("NewWay", "System.String", false, false, false, "String")]
        public string NewWay
        {
            get
            {
                return this._NewWay;
            }
            set
            {
                this._NewWay = value;
            }
        }

        /// <summary>
        /// OldSelfPickType
        /// </summary>
        [AttributeField("OldSelfPickType", "System.String", false, false, false, "String")]
        public string OldSelfPickType
        {
            get
            {
                return this._OldSelfPickType;
            }
            set
            {
                this._OldSelfPickType = value;
            }
        }

        /// <summary>
        /// NewSelfPickType
        /// </summary>
        [AttributeField("NewSelfPickType", "System.String", false, false, false, "String")]
        public string NewSelfPickType
        {
            get
            {
                return this._NewSelfPickType;
            }
            set
            {
                this._NewSelfPickType = value;
            }
        }

        /// <summary>
        /// enditem
        /// </summary>
        [AttributeField("enditem", "System.String", false, false, false, "String")]
        public string enditem
        {
            get
            {
                return this._enditem;
            }
            set
            {
                this._enditem = value;
            }
        }

        /// <summary>
        /// newitem
        /// </summary>
        [AttributeField("newitem", "System.String", false, false, false, "String")]
        public string newitem
        {
            get
            {
                return this._newitem;
            }
            set
            {
                this._newitem = value;
            }
        }

        /// <summary>
        /// oldMailno
        /// </summary>
        [AttributeField("oldMailno", "System.String", false, false, false, "String")]
        public string oldMailno
        {
            get
            {
                return this._oldMailno;
            }
            set
            {
                this._oldMailno = value;
            }
        }

        /// <summary>
        /// newmailno
        /// </summary>
        [AttributeField("newmailno", "System.String", false, false, false, "String")]
        public string newmailno
        {
            get
            {
                return this._newmailno;
            }
            set
            {
                this._newmailno = value;
            }
        }

        /// <summary>
        /// OldZip
        /// </summary>
        [AttributeField("OldZip", "System.String", false, false, false, "String")]
        public string OldZip
        {
            get
            {
                return this._OldZip;
            }
            set
            {
                this._OldZip = value;
            }
        }

        /// <summary>
        /// OldAdd1
        /// </summary>
        [AttributeField("OldAdd1", "System.String", false, false, false, "String")]
        public string OldAdd1
        {
            get
            {
                return this._OldAdd1;
            }
            set
            {
                this._OldAdd1 = value;
            }
        }

        /// <summary>
        /// OldAdd2
        /// </summary>
        [AttributeField("OldAdd2", "System.String", false, false, false, "String")]
        public string OldAdd2
        {
            get
            {
                return this._OldAdd2;
            }
            set
            {
                this._OldAdd2 = value;
            }
        }

        /// <summary>
        /// OldAdd3
        /// </summary>
        [AttributeField("OldAdd3", "System.String", false, false, false, "String")]
        public string OldAdd3
        {
            get
            {
                return this._OldAdd3;
            }
            set
            {
                this._OldAdd3 = value;
            }
        }

        /// <summary>
        /// NewZip
        /// </summary>
        [AttributeField("NewZip", "System.String", false, false, false, "String")]
        public string NewZip
        {
            get
            {
                return this._NewZip;
            }
            set
            {
                this._NewZip = value;
            }
        }

        /// <summary>
        /// NewAdd1
        /// </summary>
        [AttributeField("NewAdd1", "System.String", false, false, false, "String")]
        public string NewAdd1
        {
            get
            {
                return this._NewAdd1;
            }
            set
            {
                this._NewAdd1 = value;
            }
        }

        /// <summary>
        /// NewAdd2
        /// </summary>
        [AttributeField("NewAdd2", "System.String", false, false, false, "String")]
        public string NewAdd2
        {
            get
            {
                return this._NewAdd2;
            }
            set
            {
                this._NewAdd2 = value;
            }
        }

        /// <summary>
        /// NewAdd3
        /// </summary>
        [AttributeField("NewAdd3", "System.String", false, false, false, "String")]
        public string NewAdd3
        {
            get
            {
                return this._NewAdd3;
            }
            set
            {
                this._NewAdd3 = value;
            }
        }

        /// <summary>
        /// CNote
        /// </summary>
        [AttributeField("CNote", "System.String", false, false, false, "String")]
        public string CNote
        {
            get
            {
                return this._CNote;
            }
            set
            {
                this._CNote = value;
            }
        }

        /// <summary>
        /// photo
        /// </summary>
        [AttributeField("photo", "System.String", false, false, false, "String")]
        public string photo
        {
            get
            {
                return this._photo;
            }
            set
            {
                this._photo = value;
            }
        }

        /// <summary>
        /// UpdUser
        /// </summary>
        [AttributeField("UpdUser", "System.String", false, false, false, "String")]
        public string UpdUser
        {
            get
            {
                return this._UpdUser;
            }
            set
            {
                this._UpdUser = value;
            }
        }

        /// <summary>
        /// UpdDate
        /// </summary>
        [AttributeField("UpdDate", "System.String", false, false, false, "String")]
        public string UpdDate
        {
            get
            {
                return this._UpdDate;
            }
            set
            {
                this._UpdDate = value;
            }
        }

        /// <summary>
        /// UpdTime
        /// </summary>
        [AttributeField("UpdTime", "System.String", false, false, false, "String")]
        public string UpdTime
        {
            get
            {
                return this._UpdTime;
            }
            set
            {
                this._UpdTime = value;
            }
        }

        /// <summary>
        /// UpMark
        /// </summary>
        [AttributeField("UpMark", "System.String", false, false, false, "String")]
        public string UpMark
        {
            get
            {
                return this._UpMark;
            }
            set
            {
                this._UpMark = value;
            }
        }

        /// <summary>
        /// NoteCaptions
        /// </summary>
        [AttributeField("NoteCaptions", "System.String", false, false, false, "String")]
        public string NoteCaptions
        {
            get
            {
                return this._NoteCaptions;
            }
            set
            {
                this._NoteCaptions = value;
            }
        }

        /// <summary>
        /// CloseFlg
        /// </summary>
        [AttributeField("CloseFlg", "System.String", false, false, false, "String")]
        public string CloseFlg
        {
            get
            {
                return this._CloseFlg;
            }
            set
            {
                this._CloseFlg = value;
            }
        }

        /// <summary>
        /// MerchCode
        /// </summary>
        [AttributeField("MerchCode", "System.String", false, false, false, "String")]
        public string MerchCode
        {
            get
            {
                return this._MerchCode;
            }
            set
            {
                this._MerchCode = value;
            }
        }

        /// <summary>
        /// UrgencyFlg
        /// </summary>
        [AttributeField("UrgencyFlg", "System.String", false, false, false, "String")]
        public string UrgencyFlg
        {
            get
            {
                return this._UrgencyFlg;
            }
            set
            {
                this._UrgencyFlg = value;
            }
        }

        /// <summary>
        /// OutputFlg
        /// </summary>
        [AttributeField("OutputFlg", "System.String", false, false, false, "String")]
        public string OutputFlg
        {
            get
            {
                return this._OutputFlg;
            }
            set
            {
                this._OutputFlg = value;
            }
        }

        /// <summary>
        /// OutputDate
        /// </summary>
        [AttributeField("OutputDate", "System.String", false, false, false, "String")]
        public string OutputDate
        {
            get
            {
                return this._OutputDate;
            }
            set
            {
                this._OutputDate = value;
            }
        }

        /// <summary>
        /// OutputFileName
        /// </summary>
        [AttributeField("OutputFileName", "System.String", false, false, false, "String")]
        public string OutputFileName
        {
            get
            {
                return this._OutputFileName;
            }
            set
            {
                this._OutputFileName = value;
            }
        }

        /// <summary>
        /// SourceType
        /// </summary>
        [AttributeField("SourceType", "System.String", false, false, false, "String")]
        public string SourceType
        {
            get
            {
                return this._SourceType;
            }
            set
            {
                this._SourceType = value;
            }
        }

        /// <summary>
        /// BaseFlg
        /// </summary>
        [AttributeField("BaseFlg", "System.String", false, false, false, "String")]
        public string BaseFlg
        {
            get
            {
                return this._BaseFlg;
            }
            set
            {
                this._BaseFlg = value;
            }
        }

        /// <summary>
        /// Type_flg
        /// </summary>
        [AttributeField("Type_flg", "System.String", false, false, false, "String")]
        public string Type_flg
        {
            get
            {
                return this._Type_flg;
            }
            set
            {
                this._Type_flg = value;
            }
        }

        /// <summary>
        /// FilePath
        /// </summary>
        [AttributeField("FilePath", "System.String", false, false, false, "String")]
        public string FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
            }
        }
    }

    /// <summary>
    /// tbl_Card_DataChange
    /// </summary>
    [Serializable()]
    public class Entity_CardDataChangeSet : EntitySet<Entity_CardDataChange>
    {
    }
}
