//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_FileInfo
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_FileInfo")]
    public class Entity_FileInfo : Framework.Data.OM.Entity
    {

        private int _FileId;

        /// <summary>
        /// FileId
        /// </summary>
        public static string M_FileId = "FileId";

        private string _Job_ID;

        /// <summary>
        /// Job_ID
        /// </summary>
        public static string M_Job_ID = "Job_ID";

        private string _FtpFileName;

        /// <summary>
        /// FtpFileName
        /// </summary>
        public static string M_FtpFileName = "FtpFileName";

        private string _MerchCode;

        /// <summary>
        /// MerchCode
        /// </summary>
        public static string M_MerchCode = "MerchCode";

        private string _MerchName;

        /// <summary>
        /// MerchName
        /// </summary>
        public static string M_MerchName = "MerchName";

        private string _AMPMFlg;

        /// <summary>
        /// AMPMFlg
        /// </summary>
        public static string M_AMPMFlg = "AMPMFlg";

        private string _CardType;

        /// <summary>
        /// CardType
        /// </summary>
        public static string M_CardType = "CardType";

        private string _FtpPath;

        /// <summary>
        /// FtpPath
        /// </summary>
        public static string M_FtpPath = "FtpPath";

        private string _ZipPwd;

        /// <summary>
        /// ZipPwd
        /// </summary>
        /// <summary>
        /// 專案代號:20200031-CSIP EOS
        /// 功能說明:白箱掃描修正-HardCode
        /// 作    者:Ares JaJa
        /// 修改時間:2020/07/29
        /// </summary>
        public static string M_ZipPd = "ZipPwd";

        private string _CancelTime;

        /// <summary>
        /// CancelTime
        /// </summary>
        public static string M_CancelTime = "CancelTime";

        private string _BLKCode;

        /// <summary>
        /// BLKCode
        /// </summary>
        public static string M_BLKCode = "BLKCode";

        private string _MEMO;

        /// <summary>
        /// MEMO
        /// </summary>
        public static string M_MEMO = "MEMO";

        private string _ReasonCode;

        /// <summary>
        /// ReasonCode
        /// </summary>
        public static string M_ReasonCode = "ReasonCode";

        private string _ActionCode;

        /// <summary>
        /// ActionCode
        /// </summary>
        public static string M_ActionCode = "ActionCode";

        private string _CWBRegions;

        /// <summary>
        /// CWBRegions
        /// </summary>
        public static string M_CWBRegions = "CWBRegions";

        private string _FunctionFlg;

        /// <summary>
        /// FunctionFlg
        /// </summary>
        public static string M_FunctionFlg = "FunctionFlg";

        private string _PExpFlg;

        /// <summary>
        /// PExpFlg
        /// </summary>
        public static string M_PExpFlg = "PExpFlg";

        private string _BExpFlg;

        /// <summary>
        /// BExpFlg
        /// </summary>
        public static string M_BExpFlg = "BExpFlg";

        private string _FtpIP;

        /// <summary>
        /// FtpIP
        /// </summary>
        public static string M_FtpIP = "FtpIP";

        private string _FtpUserName;

        /// <summary>
        /// FtpUserName
        /// </summary>
        public static string M_FtpUserName = "FtpUserName";

        private string _FtpPwd;

        /// <summary>
        /// FtpPwd
        /// </summary>
        /// <summary>
        /// 專案代號:20200031-CSIP EOS
        /// 功能說明:白箱掃描修正-HardCode
        /// 作    者:Ares JaJa
        /// 修改時間:2020/07/29
        /// </summary>
        public static string M_FtpPd = "FtpPwd";

        private string _Status;

        /// <summary>
        /// Status
        /// </summary>
        public static string M_Status = "Status";

        private string _ImpSort;

        /// <summary>
        /// ImpSort
        /// </summary>
        public static string M_ImpSort = "ImpSort";

        private string _ImportDate;

        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";

        /// <summary>
        /// FileId
        /// </summary>
        [AttributeField("FileId", "System.Int32", false, true, true, "Int32")]
        public int FileId
        {
            get
            {
                return this._FileId;
            }
            set
            {
                this._FileId = value;
            }
        }

        /// <summary>
        /// Job_ID
        /// </summary>
        [AttributeField("Job_ID", "System.String", false, false, false, "String")]
        public string Job_ID
        {
            get
            {
                return this._Job_ID;
            }
            set
            {
                this._Job_ID = value;
            }
        }

        /// <summary>
        /// FtpFileName
        /// </summary>
        [AttributeField("FtpFileName", "System.String", false, false, false, "String")]
        public string FtpFileName
        {
            get
            {
                return this._FtpFileName;
            }
            set
            {
                this._FtpFileName = value;
            }
        }

        /// <summary>
        /// MerchCode
        /// </summary>
        [AttributeField("MerchCode", "System.String", false, false, false, "String")]
        public string MerchCode
        {
            get
            {
                return this._MerchCode;
            }
            set
            {
                this._MerchCode = value;
            }
        }

        /// <summary>
        /// MerchName
        /// </summary>
        [AttributeField("MerchName", "System.String", false, false, false, "String")]
        public string MerchName
        {
            get
            {
                return this._MerchName;
            }
            set
            {
                this._MerchName = value;
            }
        }

        /// <summary>
        /// AMPMFlg
        /// </summary>
        [AttributeField("AMPMFlg", "System.String", false, false, false, "String")]
        public string AMPMFlg
        {
            get
            {
                return this._AMPMFlg;
            }
            set
            {
                this._AMPMFlg = value;
            }
        }

        /// <summary>
        /// CardType
        /// </summary>
        [AttributeField("CardType", "System.String", false, false, false, "String")]
        public string CardType
        {
            get
            {
                return this._CardType;
            }
            set
            {
                this._CardType = value;
            }
        }

        /// <summary>
        /// FtpPath
        /// </summary>
        [AttributeField("FtpPath", "System.String", false, false, false, "String")]
        public string FtpPath
        {
            get
            {
                return this._FtpPath;
            }
            set
            {
                this._FtpPath = value;
            }
        }

        /// <summary>
        /// ZipPwd
        /// </summary>
        [AttributeField("ZipPwd", "System.String", false, false, false, "String")]
        public string ZipPwd
        {
            get
            {
                return this._ZipPwd;
            }
            set
            {
                this._ZipPwd = value;
            }
        }

        /// <summary>
        /// CancelTime
        /// </summary>
        [AttributeField("CancelTime", "System.String", false, false, false, "String")]
        public string CancelTime
        {
            get
            {
                return this._CancelTime;
            }
            set
            {
                this._CancelTime = value;
            }
        }

        /// <summary>
        /// BLKCode
        /// </summary>
        [AttributeField("BLKCode", "System.String", false, false, false, "String")]
        public string BLKCode
        {
            get
            {
                return this._BLKCode;
            }
            set
            {
                this._BLKCode = value;
            }
        }

        /// <summary>
        /// MEMO
        /// </summary>
        [AttributeField("MEMO", "System.String", false, false, false, "String")]
        public string MEMO
        {
            get
            {
                return this._MEMO;
            }
            set
            {
                this._MEMO = value;
            }
        }

        /// <summary>
        /// ReasonCode
        /// </summary>
        [AttributeField("ReasonCode", "System.String", false, false, false, "String")]
        public string ReasonCode
        {
            get
            {
                return this._ReasonCode;
            }
            set
            {
                this._ReasonCode = value;
            }
        }

        /// <summary>
        /// ActionCode
        /// </summary>
        [AttributeField("ActionCode", "System.String", false, false, false, "String")]
        public string ActionCode
        {
            get
            {
                return this._ActionCode;
            }
            set
            {
                this._ActionCode = value;
            }
        }

        /// <summary>
        /// CWBRegions
        /// </summary>
        [AttributeField("CWBRegions", "System.String", false, false, false, "String")]
        public string CWBRegions
        {
            get
            {
                return this._CWBRegions;
            }
            set
            {
                this._CWBRegions = value;
            }
        }

        /// <summary>
        /// FunctionFlg
        /// </summary>
        [AttributeField("FunctionFlg", "System.String", false, false, false, "String")]
        public string FunctionFlg
        {
            get
            {
                return this._FunctionFlg;
            }
            set
            {
                this._FunctionFlg = value;
            }
        }

        /// <summary>
        /// PExpFlg
        /// </summary>
        [AttributeField("PExpFlg", "System.String", false, false, false, "String")]
        public string PExpFlg
        {
            get
            {
                return this._PExpFlg;
            }
            set
            {
                this._PExpFlg = value;
            }
        }

        /// <summary>
        /// BExpFlg
        /// </summary>
        [AttributeField("BExpFlg", "System.String", false, false, false, "String")]
        public string BExpFlg
        {
            get
            {
                return this._BExpFlg;
            }
            set
            {
                this._BExpFlg = value;
            }
        }

        /// <summary>
        /// FtpIP
        /// </summary>
        [AttributeField("FtpIP", "System.String", false, false, false, "String")]
        public string FtpIP
        {
            get
            {
                return this._FtpIP;
            }
            set
            {
                this._FtpIP = value;
            }
        }

        /// <summary>
        /// FtpUserName
        /// </summary>
        [AttributeField("FtpUserName", "System.String", false, false, false, "String")]
        public string FtpUserName
        {
            get
            {
                return this._FtpUserName;
            }
            set
            {
                this._FtpUserName = value;
            }
        }

        /// <summary>
        /// FtpPwd
        /// </summary>
        [AttributeField("FtpPwd", "System.String", false, false, false, "String")]
        public string FtpPwd
        {
            get
            {
                return this._FtpPwd;
            }
            set
            {
                this._FtpPwd = value;
            }
        }

        /// <summary>
        /// Status
        /// </summary>
        [AttributeField("Status", "System.String", false, false, false, "String")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this._Status = value;
            }
        }

        /// <summary>
        /// ImpSort
        /// </summary>
        [AttributeField("ImpSort", "System.String", false, false, false, "String")]
        public string ImpSort
        {
            get
            {
                return this._ImpSort;
            }
            set
            {
                this._ImpSort = value;
            }
        }

        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }
    }

    /// <summary>
    /// tbl_FileInfo
    /// </summary>
    [Serializable()]
    public class Entity_FileInfoSet : EntitySet<Entity_FileInfo>
    {
    }
}