//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// M_AUTOJOB
    /// </summary>
    [Serializable()]
    [AttributeTable("M_AUTOJOB")]
    public class EntityM_AutoJob : Framework.Data.OM.Entity
    {
        
        private string _FUNCTION_KEY;
        
        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        public static string M_FUNCTION_KEY = "FUNCTION_KEY";
        
        private string _JOB_ID;
        
        /// <summary>
        /// JOB_ID
        /// </summary>
        public static string M_JOB_ID = "JOB_ID";
        
        private string _DESCRIPTION;
        
        /// <summary>
        /// DESCRIPTION
        /// </summary>
        public static string M_DESCRIPTION = "DESCRIPTION";
        
        private string _EXEC_PROG;
        
        /// <summary>
        /// EXEC_PROG
        /// </summary>
        public static string M_EXEC_PROG = "EXEC_PROG";
        
        private string _STATUS;
        
        /// <summary>
        /// STATUS
        /// </summary>
        public static string M_STATUS = "STATUS";
        
        private string _RUN_USER_LDAPID;
        
        /// <summary>
        /// RUN_USER_LDAPID
        /// </summary>
        public static string M_RUN_USER_LDAPID = "RUN_USER_LDAPID";
        
        private string _RUN_USER_LDAPPWD;

        /// <summary>
        /// RUN_USER_LDAPPWD
        /// </summary>
        /// <summary>
        /// 專案代號:20200031-CSIP EOS
        /// 功能說明:白箱掃描修正-HardCode
        /// 作    者:Ares JaJa
        /// 修改時間:2020/07/29
        /// </summary>
        public static string M_RUN_USER_LDAPPD = "RUN_USER_LDAPPWD";
        
        private string _RUN_USER_RACFID;
        
        /// <summary>
        /// RUN_USER_RACFID
        /// </summary>
        public static string M_RUN_USER_RACFID = "RUN_USER_RACFID";
        
        private string _RUN_USER_RACFPWD;

        /// <summary>
        /// RUN_USER_RACFPWD
        /// </summary>
        /// <summary>
        /// 專案代號:20200031-CSIP EOS
        /// 功能說明:白箱掃描修正-HardCode
        /// 作    者:Ares JaJa
        /// 修改時間:2020/07/29
        /// </summary>
        public static string M_RUN_USER_RACFPD = "RUN_USER_RACFPWD";
        
        private string _RUN_SECONDS;
        
        /// <summary>
        /// RUN_SECONDS
        /// </summary>
        public static string M_RUN_SECONDS = "RUN_SECONDS";
        
        private string _RUN_MINUTES;
        
        /// <summary>
        /// RUN_MINUTES
        /// </summary>
        public static string M_RUN_MINUTES = "RUN_MINUTES";
        
        private string _RUN_HOURS;
        
        /// <summary>
        /// RUN_HOURS
        /// </summary>
        public static string M_RUN_HOURS = "RUN_HOURS";
        
        private string _RUN_DAY_OF_MONTH;
        
        /// <summary>
        /// RUN_DAY_OF_MONTH
        /// </summary>
        public static string M_RUN_DAY_OF_MONTH = "RUN_DAY_OF_MONTH";
        
        private string _RUN_MONTH;
        
        /// <summary>
        /// RUN_MONTH
        /// </summary>
        public static string M_RUN_MONTH = "RUN_MONTH";
        
        private string _RUN_DAY_OF_WEEK;
        
        /// <summary>
        /// RUN_DAY_OF_WEEK
        /// </summary>
        public static string M_RUN_DAY_OF_WEEK = "RUN_DAY_OF_WEEK";
        
        private string _MAIL_TO;
        
        /// <summary>
        /// MAIL_TO
        /// </summary>
        public static string M_MAIL_TO = "MAIL_TO";
        
        private string _CHANGED_USER;
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        public static string M_CHANGED_USER = "CHANGED_USER";
        
        private object _CHANGED_TIME;
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        public static string M_CHANGED_TIME = "CHANGED_TIME";
        
        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        [AttributeField("FUNCTION_KEY", "System.String", false, false, false, "String")]
        public string FUNCTION_KEY
        {
            get
            {
                return this._FUNCTION_KEY;
            }
            set
            {
                this._FUNCTION_KEY = value;
            }
        }
        
        /// <summary>
        /// JOB_ID
        /// </summary>
        [AttributeField("JOB_ID", "System.String", false, false, false, "String")]
        public string JOB_ID
        {
            get
            {
                return this._JOB_ID;
            }
            set
            {
                this._JOB_ID = value;
            }
        }
        
        /// <summary>
        /// DESCRIPTION
        /// </summary>
        [AttributeField("DESCRIPTION", "System.String", false, false, false, "String")]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this._DESCRIPTION = value;
            }
        }
        
        /// <summary>
        /// EXEC_PROG
        /// </summary>
        [AttributeField("EXEC_PROG", "System.String", false, false, false, "String")]
        public string EXEC_PROG
        {
            get
            {
                return this._EXEC_PROG;
            }
            set
            {
                this._EXEC_PROG = value;
            }
        }
        
        /// <summary>
        /// STATUS
        /// </summary>
        [AttributeField("STATUS", "System.String", false, false, false, "String")]
        public string STATUS
        {
            get
            {
                return this._STATUS;
            }
            set
            {
                this._STATUS = value;
            }
        }
        
        /// <summary>
        /// RUN_USER_LDAPID
        /// </summary>
        [AttributeField("RUN_USER_LDAPID", "System.String", false, false, false, "String")]
        public string RUN_USER_LDAPID
        {
            get
            {
                return this._RUN_USER_LDAPID;
            }
            set
            {
                this._RUN_USER_LDAPID = value;
            }
        }
        
        /// <summary>
        /// RUN_USER_LDAPPWD
        /// </summary>
        [AttributeField("RUN_USER_LDAPPWD", "System.String", false, false, false, "String")]
        public string RUN_USER_LDAPPWD
        {
            get
            {
                return this._RUN_USER_LDAPPWD;
            }
            set
            {
                this._RUN_USER_LDAPPWD = value;
            }
        }
        
        /// <summary>
        /// RUN_USER_RACFID
        /// </summary>
        [AttributeField("RUN_USER_RACFID", "System.String", false, false, false, "String")]
        public string RUN_USER_RACFID
        {
            get
            {
                return this._RUN_USER_RACFID;
            }
            set
            {
                this._RUN_USER_RACFID = value;
            }
        }
        
        /// <summary>
        /// RUN_USER_RACFPWD
        /// </summary>
        [AttributeField("RUN_USER_RACFPWD", "System.String", false, false, false, "String")]
        public string RUN_USER_RACFPWD
        {
            get
            {
                return this._RUN_USER_RACFPWD;
            }
            set
            {
                this._RUN_USER_RACFPWD = value;
            }
        }
        
        /// <summary>
        /// RUN_SECONDS
        /// </summary>
        [AttributeField("RUN_SECONDS", "System.String", false, false, false, "String")]
        public string RUN_SECONDS
        {
            get
            {
                return this._RUN_SECONDS;
            }
            set
            {
                this._RUN_SECONDS = value;
            }
        }
        
        /// <summary>
        /// RUN_MINUTES
        /// </summary>
        [AttributeField("RUN_MINUTES", "System.String", false, false, false, "String")]
        public string RUN_MINUTES
        {
            get
            {
                return this._RUN_MINUTES;
            }
            set
            {
                this._RUN_MINUTES = value;
            }
        }
        
        /// <summary>
        /// RUN_HOURS
        /// </summary>
        [AttributeField("RUN_HOURS", "System.String", false, false, false, "String")]
        public string RUN_HOURS
        {
            get
            {
                return this._RUN_HOURS;
            }
            set
            {
                this._RUN_HOURS = value;
            }
        }
        
        /// <summary>
        /// RUN_DAY_OF_MONTH
        /// </summary>
        [AttributeField("RUN_DAY_OF_MONTH", "System.String", false, false, false, "String")]
        public string RUN_DAY_OF_MONTH
        {
            get
            {
                return this._RUN_DAY_OF_MONTH;
            }
            set
            {
                this._RUN_DAY_OF_MONTH = value;
            }
        }
        
        /// <summary>
        /// RUN_MONTH
        /// </summary>
        [AttributeField("RUN_MONTH", "System.String", false, false, false, "String")]
        public string RUN_MONTH
        {
            get
            {
                return this._RUN_MONTH;
            }
            set
            {
                this._RUN_MONTH = value;
            }
        }
        
        /// <summary>
        /// RUN_DAY_OF_WEEK
        /// </summary>
        [AttributeField("RUN_DAY_OF_WEEK", "System.String", false, false, false, "String")]
        public string RUN_DAY_OF_WEEK
        {
            get
            {
                return this._RUN_DAY_OF_WEEK;
            }
            set
            {
                this._RUN_DAY_OF_WEEK = value;
            }
        }
        
        /// <summary>
        /// MAIL_TO
        /// </summary>
        [AttributeField("MAIL_TO", "System.String", false, false, false, "String")]
        public string MAIL_TO
        {
            get
            {
                return this._MAIL_TO;
            }
            set
            {
                this._MAIL_TO = value;
            }
        }
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        [AttributeField("CHANGED_USER", "System.String", false, false, false, "String")]
        public string CHANGED_USER
        {
            get
            {
                return this._CHANGED_USER;
            }
            set
            {
                this._CHANGED_USER = value;
            }
        }
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        [AttributeField("CHANGED_TIME", "System.DateTime", false, false, false, "DateTime")]
        public object CHANGED_TIME
        {
            get
            {
                return this._CHANGED_TIME;
            }
            set
            {
                this._CHANGED_TIME = value;
            }
        }
    }
    
    /// <summary>
    /// M_AUTOJOB
    /// </summary>
    [Serializable()]
    public class EntityM_AUTOJOBSet : EntitySet<EntityM_AutoJob>
    {
    }
}
