//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_CancelOASA_Source
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CancelOASA_Source")]
    public class Entity_CancelOASA_Source : Framework.Data.OM.Entity
    {
        private string _ImportFile;

        /// <summary>
        /// ImportFile
        /// </summary>
        public static string M_ImportFile = "ImportFile";

        private string _ImportDate;

        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _Stauts;

        /// <summary>
        /// Stauts
        /// </summary>
        public static string M_Stauts = "Stauts";


        private string _ExpDate;

        /// <summary>
        /// Stauts
        /// </summary>
        public static string M_ExpDate = "ExpDate";

        /// <summary>
        /// ImportFile
        /// </summary>
        [AttributeField("ImportFile", "System.String", false, false, false, "String")]
        public string ImportFile
        {
            get
            {
                return this._ImportFile;
            }
            set
            {
                this._ImportFile = value;
            }
        }

        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// Stauts
        /// </summary>
        [AttributeField("Stauts", "System.String", false, false, false, "String")]
        public string Stauts
        {
            get
            {
                return this._Stauts;
            }
            set
            {
                this._Stauts = value;
            }
        }

        /// <summary>
        /// ExpDate
        /// </summary>
        [AttributeField("ExpDate", "System.String", false, false, false, "String")]
        public string ExpDate
        {
            get
            {
                return this._ExpDate;
            }
            set
            {
                this._ExpDate = value;
            }
        }
    }

    /// <summary>
    /// tbl_CancelOASA_Source
    /// </summary>
    [Serializable()]
    public class Entity_CancelOASA_SourceSet : EntitySet<Entity_CancelOASA_Source>
    {
    }
}
