//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_CardChange
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CardChange")]
    public class Entity_CardChange : Framework.Data.OM.Entity
    {

        private int _Sno;

        /// <summary>
        /// Sno
        /// </summary>
        public static string M_Sno = "Sno";

        private System.Nullable<int> _ParentSno;

        /// <summary>
        /// ParentSno
        /// </summary>
        public static string M_ParentSno = "ParentSno";

        private string _Trandate;

        /// <summary>
        /// Trandate
        /// </summary>
        public static string M_Trandate = "Trandate";

        private string _Id;

        /// <summary>
        /// Id
        /// </summary>
        public static string M_Id = "Id";

        private string _CustName;

        /// <summary>
        /// CustName
        /// </summary>
        public static string M_CustName = "CustName";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _BlockCode;

        /// <summary>
        /// BlockCode
        /// </summary>
        public static string M_BlockCode = "BlockCode";

        private string _ImportDate;

        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";

        private string _ImportFileName;

        /// <summary>
        /// ImportFileName
        /// </summary>
        public static string M_ImportFileName = "ImportFileName";

        private string _OutputFlg;

        /// <summary>
        /// OutputFlg
        /// </summary>
        public static string M_OutputFlg = "OutputFlg";

        private string _OutputDate;

        /// <summary>
        /// OutputDate
        /// </summary>
        public static string M_OutputDate = "OutputDate";

        private string _OutputFileName;

        /// <summary>
        /// OutputFileName
        /// </summary>
        public static string M_OutputFileName = "OutputFileName";

        private string _FilePath;

        /// <summary>
        /// FilePath
        /// </summary>
        public static string M_FilePath = "FilePath";

        /// <summary>
        /// Sno
        /// </summary>
        [AttributeField("Sno", "System.Int32", false, true, true, "Int32")]
        public int Sno
        {
            get
            {
                return this._Sno;
            }
            set
            {
                this._Sno = value;
            }
        }

        /// <summary>
        /// ParentSno
        /// </summary>
        [AttributeField("ParentSno", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> ParentSno
        {
            get
            {
                return this._ParentSno;
            }
            set
            {
                this._ParentSno = value;
            }
        }

        /// <summary>
        /// Trandate
        /// </summary>
        [AttributeField("Trandate", "System.String", false, false, false, "String")]
        public string Trandate
        {
            get
            {
                return this._Trandate;
            }
            set
            {
                this._Trandate = value;
            }
        }

        /// <summary>
        /// Id
        /// </summary>
        [AttributeField("Id", "System.String", false, false, false, "String")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

        /// <summary>
        /// CustName
        /// </summary>
        [AttributeField("CustName", "System.String", false, false, false, "String")]
        public string CustName
        {
            get
            {
                return this._CustName;
            }
            set
            {
                this._CustName = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// BlockCode
        /// </summary>
        [AttributeField("BlockCode", "System.String", false, false, false, "String")]
        public string BlockCode
        {
            get
            {
                return this._BlockCode;
            }
            set
            {
                this._BlockCode = value;
            }
        }

        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }

        /// <summary>
        /// ImportFileName
        /// </summary>
        [AttributeField("ImportFileName", "System.String", false, false, false, "String")]
        public string ImportFileName
        {
            get
            {
                return this._ImportFileName;
            }
            set
            {
                this._ImportFileName = value;
            }
        }

        /// <summary>
        /// OutputFlg
        /// </summary>
        [AttributeField("OutputFlg", "System.String", false, false, false, "String")]
        public string OutputFlg
        {
            get
            {
                return this._OutputFlg;
            }
            set
            {
                this._OutputFlg = value;
            }
        }

        /// <summary>
        /// OutputDate
        /// </summary>
        [AttributeField("OutputDate", "System.String", false, false, false, "String")]
        public string OutputDate
        {
            get
            {
                return this._OutputDate;
            }
            set
            {
                this._OutputDate = value;
            }
        }

        /// <summary>
        /// OutputFileName
        /// </summary>
        [AttributeField("OutputFileName", "System.String", false, false, false, "String")]
        public string OutputFileName
        {
            get
            {
                return this._OutputFileName;
            }
            set
            {
                this._OutputFileName = value;
            }
        }

        /// <summary>
        /// FilePath
        /// </summary>
        [AttributeField("FilePath", "System.String", false, false, false, "String")]
        public string FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
            }
        }

        //20210112陳永銘 新增羅馬拼音
        private string _CustName_Roma;

        /// <summary>
        /// CustName_Roma
        /// </summary>
        public static string M_CustName_Roma = "CustName_Roma";

        /// <summary>
        /// CustName_Roma
        /// </summary>
        [AttributeField("CustName_Roma", "System.String", false, false, false, "String")]
        public string CustName_Roma
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
            }
        }
    }

    /// <summary>
    /// tbl_CardChange
    /// </summary>
    [Serializable()]
    public class Entity_CardChangeSet : EntitySet<Entity_CardChange>
    {
    }
}
