//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_CancelOASA
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CancelOASA")]
    public class Entity_CancelOASA : Framework.Data.OM.Entity
    {

        private string _CancelOASAFile;

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        public static string M_CancelOASAFile = "CancelOASAFile";

        private string _CancelOASADate;

        /// <summary>
        /// CancelOASADate
        /// </summary>
        public static string M_CancelOASADate = "CancelOASADate";

        private string _CancelOASAUser;

        /// <summary>
        /// CancelOASAUser
        /// </summary>
        public static string M_CancelOASAUser = "CancelOASAUser";

        private System.Nullable<int> _TotalCount;

        /// <summary>
        /// TotalCount
        /// </summary>
        public static string M_TotalCount = "TotalCount";

        private System.Nullable<int> _SCount;

        /// <summary>
        /// SCount
        /// </summary>
        public static string M_SCount = "SCount";

        private System.Nullable<int> _FCount;

        /// <summary>
        /// FCount
        /// </summary>
        public static string M_FCount = "FCount";

        private string _CancelOASASource;

        /// <summary>
        /// CancelOASASource
        /// </summary>
        public static string M_CancelOASASource = "CancelOASASource";

        private string _Stauts;

        /// <summary>
        /// Stauts
        /// </summary>
        public static string M_Stauts = "Stauts";

        private string _ConfirmUser;

        /// <summary>
        /// ConfirmUser
        /// </summary>
        public static string M_ConfirmUser = "ConfirmUser";

        private string _ModStautsUser;

        /// <summary>
        /// ModStautsUser
        /// </summary>
        public static string M_ModStautsUser = "ModStautsUser";

        private string _ModStautsDate;

        /// <summary>
        /// ModStautsDate
        /// </summary>
        public static string M_ModStautsDate = "ModStautsDate";

        private string _ChangeNote;

        /// <summary>
        /// ChangeNote
        /// </summary>
        public static string M_ChangeNote = "ChangeNote";

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        [AttributeField("CancelOASAFile", "System.String", false, true, false, "String")]
        public string CancelOASAFile
        {
            get
            {
                return this._CancelOASAFile;
            }
            set
            {
                this._CancelOASAFile = value;
            }
        }

        /// <summary>
        /// CancelOASADate
        /// </summary>
        [AttributeField("CancelOASADate", "System.String", false, true, false, "String")]
        public string CancelOASADate
        {
            get
            {
                return this._CancelOASADate;
            }
            set
            {
                this._CancelOASADate = value;
            }
        }

        /// <summary>
        /// CancelOASAUser
        /// </summary>
        [AttributeField("CancelOASAUser", "System.String", false, false, false, "String")]
        public string CancelOASAUser
        {
            get
            {
                return this._CancelOASAUser;
            }
            set
            {
                this._CancelOASAUser = value;
            }
        }

        /// <summary>
        /// TotalCount
        /// </summary>
        [AttributeField("TotalCount", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> TotalCount
        {
            get
            {
                return this._TotalCount;
            }
            set
            {
                this._TotalCount = value;
            }
        }

        /// <summary>
        /// SCount
        /// </summary>
        [AttributeField("SCount", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> SCount
        {
            get
            {
                return this._SCount;
            }
            set
            {
                this._SCount = value;
            }
        }

        /// <summary>
        /// FCount
        /// </summary>
        [AttributeField("FCount", "System.Nullable`1[System.Int32]", false, false, false, "Int32")]
        public System.Nullable<int> FCount
        {
            get
            {
                return this._FCount;
            }
            set
            {
                this._FCount = value;
            }
        }

        /// <summary>
        /// CancelOASASource
        /// </summary>
        [AttributeField("CancelOASASource", "System.String", false, false, false, "String")]
        public string CancelOASASource
        {
            get
            {
                return this._CancelOASASource;
            }
            set
            {
                this._CancelOASASource = value;
            }
        }

        /// <summary>
        /// Stauts
        /// </summary>
        [AttributeField("Stauts", "System.String", false, false, false, "String")]
        public string Stauts
        {
            get
            {
                return this._Stauts;
            }
            set
            {
                this._Stauts = value;
            }
        }

        /// <summary>
        /// ConfirmUser
        /// </summary>
        [AttributeField("ConfirmUser", "System.String", false, false, false, "String")]
        public string ConfirmUser
        {
            get
            {
                return this._ConfirmUser;
            }
            set
            {
                this._ConfirmUser = value;
            }
        }

        /// <summary>
        /// ModStautsUser
        /// </summary>
        [AttributeField("ModStautsUser", "System.String", false, false, false, "String")]
        public string ModStautsUser
        {
            get
            {
                return this._ModStautsUser;
            }
            set
            {
                this._ModStautsUser = value;
            }
        }

        /// <summary>
        /// ModStautsDate
        /// </summary>
        [AttributeField("ModStautsDate", "System.String", false, false, false, "String")]
        public string ModStautsDate
        {
            get
            {
                return this._ModStautsDate;
            }
            set
            {
                this._ModStautsDate = value;
            }
        }

        /// <summary>
        /// ChangeNote
        /// </summary>
        [AttributeField("ChangeNote", "System.String", false, false, false, "String")]
        public string ChangeNote
        {
            get
            {
                return this._ChangeNote;
            }
            set
            {
                this._ChangeNote = value;
            }
        }
    }
    
    /// <summary>
    /// tbl_CancelOASA
    /// </summary>
    [Serializable()]
    public class Entity_CancelOASASet : EntitySet<Entity_CancelOASA>
    {
    }
}
