//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// EntityM_PROPERTY_KEY
    /// </summary>
    [Serializable()]
    [AttributeTable("M_PROPERTY_KEY")]
    public class EntityM_PROPERTY_KEY : Framework.Data.OM.Entity
    {
        
        private string _FUNCTION_KEY;
        
        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        public static string M_FUNCTION_KEY = "FUNCTION_KEY";
        
        private string _PROPERTY_KEY;
        
        /// <summary>
        /// PROPERTY_KEY
        /// </summary>
        public static string M_PROPERTY = "PROPERTY_KEY";
        
        private string _DESCRIPTION;
        
        /// <summary>
        /// DESCRIPTION
        /// </summary>
        public static string M_DESCRIPTION = "DESCRIPTION";
        
        private string _CHANGED_USER;
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        public static string M_CHANGED_USER = "CHANGED_USER";
        
        private object _CHANGED_TIME;
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        public static string M_CHANGED_TIME = "CHANGED_TIME";


        //REQ-T20090065 參數增加停用控制欄位 Added by weilin 2010/05/17 Start
        private string _OFF_FLAG;
        /// <summary>
        /// OFF_FLAG
        /// </summary>
        public static string M_OFF_FLAG = "OFF_FLAG";
        //REQ-T20090065 參數增加停用控制欄位 Added by weilin 2010/05/17 End 

        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        [AttributeField("FUNCTION_KEY", "System.String", false, true, false, "String")]
        public string FUNCTION_KEY
        {
            get
            {
                return this._FUNCTION_KEY;
            }
            set
            {
                this._FUNCTION_KEY = value;
            }
        }
        
        /// <summary>
        /// PROPERTY_KEY
        /// </summary>
        [AttributeField("PROPERTY_KEY", "System.String", false, true, false, "String")]
        public string PROPERTY_KEY
        {
            get
            {
                return this._PROPERTY_KEY;
            }
            set
            {
                this._PROPERTY_KEY = value;
            }
        }
        
        /// <summary>
        /// DESCRIPTION
        /// </summary>
        [AttributeField("DESCRIPTION", "System.String", false, false, false, "String")]
        public string DESCRIPTION
        {
            get
            {
                return this._DESCRIPTION;
            }
            set
            {
                this._DESCRIPTION = value;
            }
        }
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        [AttributeField("CHANGED_USER", "System.String", false, false, false, "String")]
        public string CHANGED_USER
        {
            get
            {
                return this._CHANGED_USER;
            }
            set
            {
                this._CHANGED_USER = value;
            }
        }
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        [AttributeField("CHANGED_TIME", "System.DateTime", false, false, false, "DateTime")]
        public object CHANGED_TIME
        {
            get
            {
                return this._CHANGED_TIME;
            }
            set
            {
                this._CHANGED_TIME = value;
            }
        }


        //REQ-T20090065 參數增加停用控制欄位 Added by weilin 2010/05/17 Start 
        /// <summary>
        /// OFF_FLAG
        /// </summary>
        [AttributeField("OFF_FLAG", "System.String", false, false, false, "String")]
        public string OFF_FLAG
        {
            get
            {
                return this._OFF_FLAG;
            }
            set
            {
                this._OFF_FLAG = value;
            }
        }
        //REQ-T20090065 參數增加停用控制欄位 Added by weilin 2010/05/17 End 
    }
    
    /// <summary>
    /// EntityM_PROPERTY_KEY
    /// </summary>
    [Serializable()]
    public class EntityM_PROPERTY_KEYSet : EntitySet<EntityM_PROPERTY_KEY>
    {
    }
}
