//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_AFFNAME
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_AFFNAME")]
    public class Entity_AffName : Framework.Data.OM.Entity
    {
        
        private string _AFFID;
        
        /// <summary>
        /// AFFID
        /// </summary>
        public static string M_AFFID = "AFFID";
        
        private string _AFFName;
        
        /// <summary>
        /// AFFName
        /// </summary>
        public static string M_AFFName = "AFFName";
        
        private string _ImportDate;
        
        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";
        
        private string _ImportFileName;
        
        /// <summary>
        /// ImportFileName
        /// </summary>
        public static string M_ImportFileName = "ImportFileName";
        
        /// <summary>
        /// AFFID
        /// </summary>
        [AttributeField("AFFID", "System.String", false, false, false, "String")]
        public string AFFID
        {
            get
            {
                return this._AFFID;
            }
            set
            {
                this._AFFID = value;
            }
        }
        
        /// <summary>
        /// AFFName
        /// </summary>
        [AttributeField("AFFName", "System.String", false, false, false, "String")]
        public string AFFName
        {
            get
            {
                return this._AFFName;
            }
            set
            {
                this._AFFName = value;
            }
        }
        
        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }
        
        /// <summary>
        /// ImportFileName
        /// </summary>
        [AttributeField("ImportFileName", "System.String", false, false, false, "String")]
        public string ImportFileName
        {
            get
            {
                return this._ImportFileName;
            }
            set
            {
                this._ImportFileName = value;
            }
        }
    }
    
    /// <summary>
    /// tbl_AFFNAME
    /// </summary>
    [Serializable()]
    public class Entity_AffNameSet : EntitySet<Entity_AffName>
    {
    }
}
