//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_CancelOASA_Detail
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CancelOASA_Detail")]
    public class Entity_CancelOASA_Detail : Framework.Data.OM.Entity
    {

        private string _CancelOASAFile;

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        public static string M_CancelOASAFile = "CancelOASAFile";

        private string _CancelOASADate;

        /// <summary>
        /// CancelOASADate
        /// </summary>
        public static string M_CancelOASADate = "CancelOASADate";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _SFFlg;

        /// <summary>
        /// SFFlg
        /// </summary>
        public static string M_SFFlg = "SFFlg";

        private string _BlockLog;

        /// <summary>
        /// BlockLog
        /// </summary>
        public static string M_BlockLog = "BlockLog";

        private string _MemoLog;

        /// <summary>
        /// MemoLog
        /// </summary>
        public static string M_MemoLog = "MemoLog";

        private string _BlockCode;

        /// <summary>
        /// BlockCode
        /// </summary>
        public static string M_BlockCode = "BlockCode";

        private string _Memo;

        /// <summary>
        /// Memo
        /// </summary>
        public static string M_Memo = "Memo";

        private string _ReasonCode;

        /// <summary>
        /// ReasonCode
        /// </summary>
        public static string M_ReasonCode = "ReasonCode";

        private string _ActionCode;

        /// <summary>
        /// ActionCode
        /// </summary>
        public static string M_ActionCode = "ActionCode";

        private string _CWBRegions;

        /// <summary>
        /// CWBRegions
        /// </summary>
        public static string M_CWBRegions = "CWBRegions";

        private string _ModSFFlgUser;

        /// <summary>
        /// ModSFFlgUser
        /// </summary>
        public static string M_ModSFFlgUser = "ModSFFlgUser";

        private string _ModSFFlgDate;

        /// <summary>
        /// ModSFFlgDate
        /// </summary>
        public static string M_ModSFFlgDate = "ModSFFlgDate";

        private string _RptType;

        /// <summary>
        /// RptType
        /// </summary>
        public static string M_RptType = "RptType";

        private string _CardNo2;

        /// <summary>
        /// CardNo2
        /// </summary>
        public static string M_CardNo2 = "CardNo2";

        private string _CusID;

        /// <summary>
        /// CusID
        /// </summary>
        public static string M_CusID = "CusID";

        private string _CardType;

        /// <summary>
        /// CardType
        /// </summary>
        public static string M_CardType = "CardType";

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        [AttributeField("CancelOASAFile", "System.String", false, true, false, "String")]
        public string CancelOASAFile
        {
            get
            {
                return this._CancelOASAFile;
            }
            set
            {
                this._CancelOASAFile = value;
            }
        }

        /// <summary>
        /// CancelOASADate
        /// </summary>
        [AttributeField("CancelOASADate", "System.String", false, true, false, "String")]
        public string CancelOASADate
        {
            get
            {
                return this._CancelOASADate;
            }
            set
            {
                this._CancelOASADate = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, true, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// SFFlg
        /// </summary>
        [AttributeField("SFFlg", "System.String", false, false, false, "String")]
        public string SFFlg
        {
            get
            {
                return this._SFFlg;
            }
            set
            {
                this._SFFlg = value;
            }
        }

        /// <summary>
        /// BlockLog
        /// </summary>
        [AttributeField("BlockLog", "System.String", false, false, false, "String")]
        public string BlockLog
        {
            get
            {
                return this._BlockLog;
            }
            set
            {
                this._BlockLog = value;
            }
        }

        /// <summary>
        /// MemoLog
        /// </summary>
        [AttributeField("MemoLog", "System.String", false, false, false, "String")]
        public string MemoLog
        {
            get
            {
                return this._MemoLog;
            }
            set
            {
                this._MemoLog = value;
            }
        }

        /// <summary>
        /// BlockCode
        /// </summary>
        [AttributeField("BlockCode", "System.String", false, false, false, "String")]
        public string BlockCode
        {
            get
            {
                return this._BlockCode;
            }
            set
            {
                this._BlockCode = value;
            }
        }

        /// <summary>
        /// Memo
        /// </summary>
        [AttributeField("Memo", "System.String", false, false, false, "String")]
        public string Memo
        {
            get
            {
                return this._Memo;
            }
            set
            {
                this._Memo = value;
            }
        }

        /// <summary>
        /// ReasonCode
        /// </summary>
        [AttributeField("ReasonCode", "System.String", false, false, false, "String")]
        public string ReasonCode
        {
            get
            {
                return this._ReasonCode;
            }
            set
            {
                this._ReasonCode = value;
            }
        }

        /// <summary>
        /// ActionCode
        /// </summary>
        [AttributeField("ActionCode", "System.String", false, false, false, "String")]
        public string ActionCode
        {
            get
            {
                return this._ActionCode;
            }
            set
            {
                this._ActionCode = value;
            }
        }

        /// <summary>
        /// CWBRegions
        /// </summary>
        [AttributeField("CWBRegions", "System.String", false, false, false, "String")]
        public string CWBRegions
        {
            get
            {
                return this._CWBRegions;
            }
            set
            {
                this._CWBRegions = value;
            }
        }

        /// <summary>
        /// ModSFFlgUser
        /// </summary>
        [AttributeField("ModSFFlgUser", "System.String", false, false, false, "String")]
        public string ModSFFlgUser
        {
            get
            {
                return this._ModSFFlgUser;
            }
            set
            {
                this._ModSFFlgUser = value;
            }
        }

        /// <summary>
        /// ModSFFlgDate
        /// </summary>
        [AttributeField("ModSFFlgDate", "System.String", false, false, false, "String")]
        public string ModSFFlgDate
        {
            get
            {
                return this._ModSFFlgDate;
            }
            set
            {
                this._ModSFFlgDate = value;
            }
        }

        /// <summary>
        /// RptType
        /// </summary>
        [AttributeField("RptType", "System.String", false, false, false, "String")]
        public string RptType
        {
            get
            {
                return this._RptType;
            }
            set
            {
                this._RptType = value;
            }
        }

        /// <summary>
        /// CardNo2
        /// </summary>
        [AttributeField("CardNo2", "System.String", false, false, false, "String")]
        public string CardNo2
        {
            get
            {
                return this._CardNo2;
            }
            set
            {
                this._CardNo2 = value;
            }
        }

        /// <summary>
        /// CusID
        /// </summary>
        [AttributeField("CusID", "System.String", false, false, false, "String")]
        public string CusID
        {
            get
            {
                return this._CusID;
            }
            set
            {
                this._CusID = value;
            }
        }

        /// <summary>
        /// CardType
        /// </summary>
        [AttributeField("CardType", "System.String", false, false, false, "String")]
        public string CardType
        {
            get
            {
                return this._CardType;
            }
            set
            {
                this._CardType = value;
            }
        }
    }

    /// <summary>
    /// tbl_CancelOASA
    /// </summary>
    [Serializable()]
    public class Entity_CancelOASA_DetailSet : EntitySet<Entity_CancelOASA_Detail>
    {
    }
}
