//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_CallMail
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CallMail")]
    public class EntityM_CallMail : Framework.Data.OM.Entity
    {

        private string _MailID;

        /// <summary>
        /// MailID
        /// </summary>
        public static string M_MailID = "MailID";

        private string _JobID;

        /// <summary>
        /// JobID
        /// </summary>
        public static string M_JobID = "JobID";

        private string _JobName;

        /// <summary>
        /// JobName
        /// </summary>
        public static string M_JobName = "JobName";

        private string _ConditionID;

        /// <summary>
        /// ConditionID
        /// </summary>
        public static string M_ConditionID = "ConditionID";

        private string _ConditionName;

        /// <summary>
        /// ConditionName
        /// </summary>
        public static string M_ConditionName = "ConditionName";

        private string _MailTittle;

        /// <summary>
        /// MailTittle
        /// </summary>
        public static string M_MailTittle = "MailTittle";

        private string _MailContext;

        /// <summary>
        /// MailContext
        /// </summary>
        public static string M_MailContext = "MailContext";

        private string _ToUserName;

        /// <summary>
        /// ToUserName
        /// </summary>
        public static string M_ToUserName = "ToUserName";

        private string _ToUsers;

        /// <summary>
        /// ToUsers
        /// </summary>
        public static string M_ToUsers = "ToUsers";

        private string _CcUserName;

        /// <summary>
        /// CcUserName
        /// </summary>
        public static string M_CcUserName = "CcUserName";

        private string _CcUsers;

        /// <summary>
        /// CcUsers
        /// </summary>
        public static string M_CcUsers = "CcUsers";

        private string _InsertUser;

        /// <summary>
        /// InsertUser
        /// </summary>
        public static string M_InsertUser = "InsertUser";

        private string _InsertDate;

        /// <summary>
        /// InsertDate
        /// </summary>
        public static string M_InsertDate = "InsertDate";

        private string _UpdataUser;

        /// <summary>
        /// UpdataUser
        /// </summary>
        public static string M_UpdataUser = "UpdataUser";

        private string _UpdataDate;

        /// <summary>
        /// UpdataDate
        /// </summary>
        public static string M_UpdataDate = "UpdataDate";

        /// <summary>
        /// MailID
        /// </summary>
        [AttributeField("MailID", "System.String", false, false, false, "String")]
        public string MailID
        {
            get
            {
                return this._MailID;
            }
            set
            {
                this._MailID = value;
            }
        }

        /// <summary>
        /// JobID
        /// </summary>
        [AttributeField("JobID", "System.String", false, false, false, "String")]
        public string JobID
        {
            get
            {
                return this._JobID;
            }
            set
            {
                this._JobID = value;
            }
        }

        /// <summary>
        /// JobName
        /// </summary>
        [AttributeField("JobName", "System.String", false, false, false, "String")]
        public string JobName
        {
            get
            {
                return this._JobName;
            }
            set
            {
                this._JobName = value;
            }
        }

        /// <summary>
        /// ConditionID
        /// </summary>
        [AttributeField("ConditionID", "System.String", false, false, false, "String")]
        public string ConditionID
        {
            get
            {
                return this._ConditionID;
            }
            set
            {
                this._ConditionID = value;
            }
        }

        /// <summary>
        /// ConditionName
        /// </summary>
        [AttributeField("ConditionName", "System.String", false, false, false, "String")]
        public string ConditionName
        {
            get
            {
                return this._ConditionName;
            }
            set
            {
                this._ConditionName = value;
            }
        }

        /// <summary>
        /// MailTittle
        /// </summary>
        [AttributeField("MailTittle", "System.String", false, false, false, "String")]
        public string MailTittle
        {
            get
            {
                return this._MailTittle;
            }
            set
            {
                this._MailTittle = value;
            }
        }

        /// <summary>
        /// MailContext
        /// </summary>
        [AttributeField("MailContext", "System.String", false, false, false, "String")]
        public string MailContext
        {
            get
            {
                return this._MailContext;
            }
            set
            {
                this._MailContext = value;
            }
        }

        /// <summary>
        /// ToUserName
        /// </summary>
        [AttributeField("ToUserName", "System.String", false, false, false, "String")]
        public string ToUserName
        {
            get
            {
                return this._ToUserName;
            }
            set
            {
                this._ToUserName = value;
            }
        }

        /// <summary>
        /// ToUsers
        /// </summary>
        [AttributeField("ToUsers", "System.String", false, false, false, "String")]
        public string ToUsers
        {
            get
            {
                return this._ToUsers;
            }
            set
            {
                this._ToUsers = value;
            }
        }

        /// <summary>
        /// CcUserName
        /// </summary>
        [AttributeField("CcUserName", "System.String", false, false, false, "String")]
        public string CcUserName
        {
            get
            {
                return this._CcUserName;
            }
            set
            {
                this._CcUserName = value;
            }
        }

        /// <summary>
        /// CcUsers
        /// </summary>
        [AttributeField("CcUsers", "System.String", false, false, false, "String")]
        public string CcUsers
        {
            get
            {
                return this._CcUsers;
            }
            set
            {
                this._CcUsers = value;
            }
        }

        /// <summary>
        /// InsertUser
        /// </summary>
        [AttributeField("InsertUser", "System.String", false, false, false, "String")]
        public string InsertUser
        {
            get
            {
                return this._InsertUser;
            }
            set
            {
                this._InsertUser = value;
            }
        }

        /// <summary>
        /// InsertDate
        /// </summary>
        [AttributeField("InsertDate", "System.String", false, false, false, "String")]
        public string InsertDate
        {
            get
            {
                return this._InsertDate;
            }
            set
            {
                this._InsertDate = value;
            }
        }

        /// <summary>
        /// UpdataUser
        /// </summary>
        [AttributeField("UpdataUser", "System.String", false, false, false, "String")]
        public string UpdataUser
        {
            get
            {
                return this._UpdataUser;
            }
            set
            {
                this._UpdataUser = value;
            }
        }

        /// <summary>
        /// UpdataDate
        /// </summary>
        [AttributeField("UpdataDate", "System.String", false, false, false, "String")]
        public string UpdataDate
        {
            get
            {
                return this._UpdataDate;
            }
            set
            {
                this._UpdataDate = value;
            }
        }
    }

    /// <summary>
    /// tbl_CallMail
    /// </summary>
    [Serializable()]
    public class EntityM_CallMailSet : EntitySet<EntityM_CallMail>
    {
    }
}
