//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// EntityM_PROPERTY_CODE
    /// </summary>
    [Serializable()]
    [AttributeTable("M_PROPERTY_CODE")]
    public class EntityM_PROPERTY_CODE : Framework.Data.OM.Entity
    {
        
        private string _FUNCTION_KEY;
        
        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        public static string M_FUNCTION_KEY = "FUNCTION_KEY";
        
        private string _PROPERTY_KEY;
        
        /// <summary>
        /// PROPERTY_KEY
        /// </summary>
        public static string M_PROPERTY_KEY = "PROPERTY_KEY";
        
        private string _PROPERTY_CODE;
        
        /// <summary>
        /// PROPERTY_CODE
        /// </summary>
        public static string M_PROPERTY = "PROPERTY_CODE";
        
        private string _PROPERTY_NAME;
        
        /// <summary>
        /// PROPERTY_NAME
        /// </summary>
        public static string M_PROPERTY_NAME = "PROPERTY_NAME";
        
        private int _SEQUENCE;
        
        /// <summary>
        /// SEQUENCE
        /// </summary>
        public static string M_SEQUENCE = "SEQUENCE";
        
        private string _CHANGED_USER;
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        public static string M_CHANGED_USER = "CHANGED_USER";
        
        private object _CHANGED_TIME;
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        public static string M_CHANGED_TIME = "CHANGED_TIME";
        
        /// <summary>
        /// FUNCTION_KEY
        /// </summary>
        [AttributeField("FUNCTION_KEY", "System.String", false, true, false, "String")]
        public string FUNCTION_KEY
        {
            get
            {
                return this._FUNCTION_KEY;
            }
            set
            {
                this._FUNCTION_KEY = value;
            }
        }
        
        /// <summary>
        /// PROPERTY_KEY
        /// </summary>
        [AttributeField("PROPERTY_KEY", "System.String", false, true, false, "String")]
        public string PROPERTY_KEY
        {
            get
            {
                return this._PROPERTY_KEY;
            }
            set
            {
                this._PROPERTY_KEY = value;
            }
        }
        
        /// <summary>
        /// PROPERTY_CODE
        /// </summary>
        [AttributeField("PROPERTY_CODE", "System.String", false, false, false, "String")]
        public string PROPERTY_CODE
        {
            get
            {
                return this._PROPERTY_CODE;
            }
            set
            {
                this._PROPERTY_CODE = value;
            }
        }
        
        /// <summary>
        /// PROPERTY_NAME
        /// </summary>
        [AttributeField("PROPERTY_NAME", "System.String", false, false, false, "String")]
        public string PROPERTY_NAME
        {
            get
            {
                return this._PROPERTY_NAME;
            }
            set
            {
                this._PROPERTY_NAME = value;
            }
        }
        
        /// <summary>
        /// SEQUENCE
        /// </summary>
        [AttributeField("SEQUENCE", "System.Int32", false, false, false, "Int32")]
        public int SEQUENCE
        {
            get
            {
                return this._SEQUENCE;
            }
            set
            {
                this._SEQUENCE = value;
            }
        }
        
        /// <summary>
        /// CHANGED_USER
        /// </summary>
        [AttributeField("CHANGED_USER", "System.String", false, false, false, "String")]
        public string CHANGED_USER
        {
            get
            {
                return this._CHANGED_USER;
            }
            set
            {
                this._CHANGED_USER = value;
            }
        }
        
        /// <summary>
        /// CHANGED_TIME
        /// </summary>
        [AttributeField("CHANGED_TIME", "System.DateTime", false, false, false, "DateTime")]
        public object CHANGED_TIME
        {
            get
            {
                return this._CHANGED_TIME;
            }
            set
            {
                this._CHANGED_TIME = value;
            }
        }
    }
    
    /// <summary>
    /// M_PROPERTY_CODE
    /// </summary>
    [Serializable()]
    public class EntityM_PROPERTY_CODESet : EntitySet<EntityM_PROPERTY_CODE>
    {
    }
}
