//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_CancelOASA_UD
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CancelOASA_UD")]
    public class Entity_CancelOASAUd : Framework.Data.OM.Entity
    {
        
       
        private string _CardNo;
        
        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";
        
        private string _CardType;
        
        /// <summary>
        /// CardType
        /// </summary>
        public static string M_CardType = "CardType";
        
        private string _PurgeDate;
        
        /// <summary>
        /// PurgeDate
        /// </summary>
        public static string M_PurgeDate = "PurgeDate";
        
        private string _SourceTypeCode;
        
        /// <summary>
        /// SourceTypeCode
        /// </summary>
        public static string M_SourceTypeCode = "SourceTypeCode";
        
        private string _OBLKCode;
        
        /// <summary>
        /// OBLKCode
        /// </summary>
        public static string M_OBLKCode = "OBLKCode";
        
        private string _NBLKCode;
        
        /// <summary>
        /// NBLKCode
        /// </summary>
        public static string M_NBLKCode = "NBLKCode";
        
        private string _MEMO;
        
        /// <summary>
        /// MEMO
        /// </summary>
        public static string M_MEMO = "MEMO";
        
        private string _Reason_Code;
        
        /// <summary>
        /// Reason_Code
        /// </summary>
        public static string M_Reason_Code = "Reason_Code";
        
        private string _Action_Code;
        
        /// <summary>
        /// Action_Code
        /// </summary>
        public static string M_Action_Code = "Action_Code";
        
        private string _Cwb_Regions;
        
        /// <summary>
        /// Cwb_Regions
        /// </summary>
        public static string M_Cwb_Regions = "Cwb_Regions";
        
        private string _PermitDate;
        
        /// <summary>
        /// PermitDate
        /// </summary>
        public static string M_PermitDate = "PermitDate";
        
        private string _SendDate;
        
        /// <summary>
        /// SendDate
        /// </summary>
        public static string M_SendDate = "SendDate";
        
        private string _CardType2;
        
        /// <summary>
        /// CardType2
        /// </summary>
        public static string M_CardType2 = "CardType2";
        
        private string _FileCode;
        
        /// <summary>
        /// FileCode
        /// </summary>
        public static string M_FileCode = "FileCode";
        
        private string _Success_Flag;
        
        /// <summary>
        /// Success_Flag
        /// </summary>
        public static string M_Success_Flag = "Success_Flag";
        
        private string _Fail_Reason;
        
        /// <summary>
        /// Fail_Reason
        /// </summary>
        public static string M_Fail_Reason = "Fail_Reason";
        
        private string _Sys_Date;
        
        /// <summary>
        /// Sys_Date
        /// </summary>
        public static string M_Sys_Date = "Sys_Date";
        
        private string _File_Date;
        
        /// <summary>
        /// File_Date
        /// </summary>
        public static string M_File_Date = "File_Date";
        
        private string _FileName_Real;
        
        /// <summary>
        /// FileName_Real
        /// </summary>
        public static string M_FileName_Real = "FileName_Real";
        
        private string _UpdUser;
        
        /// <summary>
        /// UpdUser
        /// </summary>
        public static string M_UpdUser = "UpdUser";
        
        private string _IN_HOUSE_FLAG;
        
        /// <summary>
        /// IN_HOUSE_FLAG
        /// </summary>
        public static string M_IN_HOUSE_FLAG = "IN_HOUSE_FLAG";
        
        private string _FileName;
        
        /// <summary>
        /// FileName
        /// </summary>
        public static string M_FileName = "FileName";
        
        private string _FailFlag;
        
        /// <summary>
        /// FailFlag
        /// </summary>
        public static string M_FailFlag = "FailFlag";
               
        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }
        
        /// <summary>
        /// CardType
        /// </summary>
        [AttributeField("CardType", "System.String", false, false, false, "String")]
        public string CardType
        {
            get
            {
                return this._CardType;
            }
            set
            {
                this._CardType = value;
            }
        }
        
        /// <summary>
        /// PurgeDate
        /// </summary>
        [AttributeField("PurgeDate", "System.String", false, false, false, "String")]
        public string PurgeDate
        {
            get
            {
                return this._PurgeDate;
            }
            set
            {
                this._PurgeDate = value;
            }
        }
        
        /// <summary>
        /// SourceTypeCode
        /// </summary>
        [AttributeField("SourceTypeCode", "System.String", false, false, false, "String")]
        public string SourceTypeCode
        {
            get
            {
                return this._SourceTypeCode;
            }
            set
            {
                this._SourceTypeCode = value;
            }
        }
        
        /// <summary>
        /// OBLKCode
        /// </summary>
        [AttributeField("OBLKCode", "System.String", false, false, false, "String")]
        public string OBLKCode
        {
            get
            {
                return this._OBLKCode;
            }
            set
            {
                this._OBLKCode = value;
            }
        }
        
        /// <summary>
        /// NBLKCode
        /// </summary>
        [AttributeField("NBLKCode", "System.String", false, false, false, "String")]
        public string NBLKCode
        {
            get
            {
                return this._NBLKCode;
            }
            set
            {
                this._NBLKCode = value;
            }
        }
        
        /// <summary>
        /// MEMO
        /// </summary>
        [AttributeField("MEMO", "System.String", false, false, false, "String")]
        public string MEMO
        {
            get
            {
                return this._MEMO;
            }
            set
            {
                this._MEMO = value;
            }
        }
        
        /// <summary>
        /// Reason_Code
        /// </summary>
        [AttributeField("Reason_Code", "System.String", false, false, false, "String")]
        public string Reason_Code
        {
            get
            {
                return this._Reason_Code;
            }
            set
            {
                this._Reason_Code = value;
            }
        }
        
        /// <summary>
        /// Action_Code
        /// </summary>
        [AttributeField("Action_Code", "System.String", false, false, false, "String")]
        public string Action_Code
        {
            get
            {
                return this._Action_Code;
            }
            set
            {
                this._Action_Code = value;
            }
        }
        
        /// <summary>
        /// Cwb_Regions
        /// </summary>
        [AttributeField("Cwb_Regions", "System.String", false, false, false, "String")]
        public string Cwb_Regions
        {
            get
            {
                return this._Cwb_Regions;
            }
            set
            {
                this._Cwb_Regions = value;
            }
        }
        
        /// <summary>
        /// PermitDate
        /// </summary>
        [AttributeField("PermitDate", "System.String", false, false, false, "String")]
        public string PermitDate
        {
            get
            {
                return this._PermitDate;
            }
            set
            {
                this._PermitDate = value;
            }
        }
        
        /// <summary>
        /// SendDate
        /// </summary>
        [AttributeField("SendDate", "System.String", false, false, false, "String")]
        public string SendDate
        {
            get
            {
                return this._SendDate;
            }
            set
            {
                this._SendDate = value;
            }
        }
        
        /// <summary>
        /// CardType2
        /// </summary>
        [AttributeField("CardType2", "System.String", false, false, false, "String")]
        public string CardType2
        {
            get
            {
                return this._CardType2;
            }
            set
            {
                this._CardType2 = value;
            }
        }
        
        /// <summary>
        /// FileCode
        /// </summary>
        [AttributeField("FileCode", "System.String", false, false, false, "String")]
        public string FileCode
        {
            get
            {
                return this._FileCode;
            }
            set
            {
                this._FileCode = value;
            }
        }
        
        /// <summary>
        /// Success_Flag
        /// </summary>
        [AttributeField("Success_Flag", "System.String", false, false, false, "String")]
        public string Success_Flag
        {
            get
            {
                return this._Success_Flag;
            }
            set
            {
                this._Success_Flag = value;
            }
        }
        
        /// <summary>
        /// Fail_Reason
        /// </summary>
        [AttributeField("Fail_Reason", "System.String", false, false, false, "String")]
        public string Fail_Reason
        {
            get
            {
                return this._Fail_Reason;
            }
            set
            {
                this._Fail_Reason = value;
            }
        }
        
        /// <summary>
        /// Sys_Date
        /// </summary>
        [AttributeField("Sys_Date", "System.String", false, false, false, "String")]
        public string Sys_Date
        {
            get
            {
                return this._Sys_Date;
            }
            set
            {
                this._Sys_Date = value;
            }
        }
        
        /// <summary>
        /// File_Date
        /// </summary>
        [AttributeField("File_Date", "System.String", false, false, false, "String")]
        public string File_Date
        {
            get
            {
                return this._File_Date;
            }
            set
            {
                this._File_Date = value;
            }
        }
        
        /// <summary>
        /// FileName_Real
        /// </summary>
        [AttributeField("FileName_Real", "System.String", false, false, false, "String")]
        public string FileName_Real
        {
            get
            {
                return this._FileName_Real;
            }
            set
            {
                this._FileName_Real = value;
            }
        }
        
        /// <summary>
        /// UpdUser
        /// </summary>
        [AttributeField("UpdUser", "System.String", false, false, false, "String")]
        public string UpdUser
        {
            get
            {
                return this._UpdUser;
            }
            set
            {
                this._UpdUser = value;
            }
        }
        
        /// <summary>
        /// IN_HOUSE_FLAG
        /// </summary>
        [AttributeField("IN_HOUSE_FLAG", "System.String", false, false, false, "String")]
        public string IN_HOUSE_FLAG
        {
            get
            {
                return this._IN_HOUSE_FLAG;
            }
            set
            {
                this._IN_HOUSE_FLAG = value;
            }
        }
        
        /// <summary>
        /// FileName
        /// </summary>
        [AttributeField("FileName", "System.String", false, false, false, "String")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this._FileName = value;
            }
        }
        
        /// <summary>
        /// FailFlag
        /// </summary>
        [AttributeField("FailFlag", "System.String", false, false, false, "String")]
        public string FailFlag
        {
            get
            {
                return this._FailFlag;
            }
            set
            {
                this._FailFlag = value;
            }
        }
    }
    /// <summary>
    /// tbl_CancelOASA_UD
    /// </summary>
    [Serializable()]
    public class Entity_CancelOASAUdSet : EntitySet<Entity_CancelOASAUd>
    {
    }
}
