//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3603
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_JobErrorInfo
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_JobErrorInfo")]
    public class Entity_JobErrorInfo : Framework.Data.OM.Entity
    {
        
        private int _ErrorID;
        
        /// <summary>
        /// ErrorID
        /// </summary>
        public static string M_ErrorID = "ErrorID";
        
        private string _JobID;
        
        /// <summary>
        /// JobID
        /// </summary>
        public static string M_JobID = "JobID";
        
        private string _ImportFileName;
        
        /// <summary>
        /// ImportFileName
        /// </summary>
        public static string M_ImportFileName = "ImportFileName";
        
        private string _ErrorContext;
        
        /// <summary>
        /// ErrorContext
        /// </summary>
        public static string M_ErrorContext = "ErrorContext";
        
        private string _ImportTime;
        
        /// <summary>
        /// ImportTime
        /// </summary>
        public static string M_ImportTime = "ImportTime";
        
        private string _Reason;
        
        /// <summary>
        /// Reason
        /// </summary>
        public static string M_Reason = "Reason";
        
        private string _LoadFlag;
        
        /// <summary>
        /// LoadFlag
        /// </summary>
        public static string M_LoadFlag = "LoadFlag";
        
        private string _LocalFilePath;
        
        /// <summary>
        /// LocalFilePath
        /// </summary>
        public static string M_LocalFilePath = "LocalFilePath";
        
        /// <summary>
        /// ErrorID
        /// </summary>
        [AttributeField("ErrorID", "System.Int32", false, true, true, "Int32")]
        public int ErrorID
        {
            get
            {
                return this._ErrorID;
            }
            set
            {
                this._ErrorID = value;
            }
        }
        
        /// <summary>
        /// JobID
        /// </summary>
        [AttributeField("JobID", "System.String", false, false, false, "String")]
        public string JobID
        {
            get
            {
                return this._JobID;
            }
            set
            {
                this._JobID = value;
            }
        }
        
        /// <summary>
        /// ImportFileName
        /// </summary>
        [AttributeField("ImportFileName", "System.String", false, false, false, "String")]
        public string ImportFileName
        {
            get
            {
                return this._ImportFileName;
            }
            set
            {
                this._ImportFileName = value;
            }
        }
        
        /// <summary>
        /// ErrorContext
        /// </summary>
        [AttributeField("ErrorContext", "System.String", false, false, false, "String")]
        public string ErrorContext
        {
            get
            {
                return this._ErrorContext;
            }
            set
            {
                this._ErrorContext = value;
            }
        }
        
        /// <summary>
        /// ImportTime
        /// </summary>
        [AttributeField("ImportTime", "System.String", false, false, false, "String")]
        public string ImportTime
        {
            get
            {
                return this._ImportTime;
            }
            set
            {
                this._ImportTime = value;
            }
        }
        
        /// <summary>
        /// Reason
        /// </summary>
        [AttributeField("Reason", "System.String", false, false, false, "String")]
        public string Reason
        {
            get
            {
                return this._Reason;
            }
            set
            {
                this._Reason = value;
            }
        }
        
        /// <summary>
        /// LoadFlag
        /// </summary>
        [AttributeField("LoadFlag", "System.String", false, false, false, "String")]
        public string LoadFlag
        {
            get
            {
                return this._LoadFlag;
            }
            set
            {
                this._LoadFlag = value;
            }
        }
        
        /// <summary>
        /// LocalFilePath
        /// </summary>
        [AttributeField("LocalFilePath", "System.String", false, false, false, "String")]
        public string LocalFilePath
        {
            get
            {
                return this._LocalFilePath;
            }
            set
            {
                this._LocalFilePath = value;
            }
        }
    }
    
    /// <summary>
    /// tbl_JobErrorInfo
    /// </summary>
    [Serializable()]
    public class Entity_JobErrorInfoSet : EntitySet<Entity_JobErrorInfo>
    {
    }
}
