//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.3615
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_UnableCard
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_UnableCard")]
    public class Entity_UnableCard : Framework.Data.OM.Entity
    {

        private int _Sno;

        /// <summary>
        /// Sno
        /// </summary>
        public static string M_Sno = "Sno";

        private string _ParentSno;

        /// <summary>
        /// ParentSno
        /// </summary>
        public static string M_ParentSno = "ParentSno";

        private string _indate1;

        /// <summary>
        /// indate1
        /// </summary>
        public static string M_indate1 = "indate1";

        private string _id;

        /// <summary>
        /// id
        /// </summary>
        public static string M_id = "id";

        private string _CustName;

        /// <summary>
        /// CustName
        /// </summary>
        public static string M_CustName = "CustName";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _blockcode;

        /// <summary>
        /// blockcode
        /// </summary>
        public static string M_blockcode = "blockcode";

        private string _ImportDate;

        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";

        private string _ImportFileName;

        /// <summary>
        /// ImportFileName
        /// </summary>
        public static string M_ImportFileName = "ImportFileName";

        private string _OutputFlg;

        /// <summary>
        /// OutputFlg
        /// </summary>
        public static string M_OutputFlg = "OutputFlg";

        private string _OutputDate;

        /// <summary>
        /// OutputDate
        /// </summary>
        public static string M_OutputDate = "OutputDate";

        private string _OutputFileName;

        /// <summary>
        /// OutputFileName
        /// </summary>
        public static string M_OutputFileName = "OutputFileName";

        private string _FilePath;

        /// <summary>
        /// FilePath
        /// </summary>
        public static string M_FilePath = "FilePath";

        private string _Action;

        /// <summary>
        /// Action
        /// </summary>
        public static string M_Action = "Action";

        /// <summary>
        /// Sno
        /// </summary>
        [AttributeField("Sno", "System.Int32", false, true, true, "Int32")]
        public int Sno
        {
            get
            {
                return this._Sno;
            }
            set
            {
                this._Sno = value;
            }
        }

        /// <summary>
        /// ParentSno
        /// </summary>
        [AttributeField("ParentSno", "System.String", false, false, false, "String")]
        public string ParentSno
        {
            get
            {
                return this._ParentSno;
            }
            set
            {
                this._ParentSno = value;
            }
        }

        /// <summary>
        /// indate1
        /// </summary>
        [AttributeField("indate1", "System.String", false, false, false, "String")]
        public string indate1
        {
            get
            {
                return this._indate1;
            }
            set
            {
                this._indate1 = value;
            }
        }

        /// <summary>
        /// id
        /// </summary>
        [AttributeField("id", "System.String", false, false, false, "String")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        /// CustName
        /// </summary>
        [AttributeField("CustName", "System.String", false, false, false, "String")]
        public string CustName
        {
            get
            {
                return this._CustName;
            }
            set
            {
                this._CustName = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// blockcode
        /// </summary>
        [AttributeField("blockcode", "System.String", false, false, false, "String")]
        public string blockcode
        {
            get
            {
                return this._blockcode;
            }
            set
            {
                this._blockcode = value;
            }
        }

        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }

        /// <summary>
        /// ImportFileName
        /// </summary>
        [AttributeField("ImportFileName", "System.String", false, false, false, "String")]
        public string ImportFileName
        {
            get
            {
                return this._ImportFileName;
            }
            set
            {
                this._ImportFileName = value;
            }
        }

        /// <summary>
        /// OutputFlg
        /// </summary>
        [AttributeField("OutputFlg", "System.String", false, false, false, "String")]
        public string OutputFlg
        {
            get
            {
                return this._OutputFlg;
            }
            set
            {
                this._OutputFlg = value;
            }
        }

        /// <summary>
        /// OutputDate
        /// </summary>
        [AttributeField("OutputDate", "System.String", false, false, false, "String")]
        public string OutputDate
        {
            get
            {
                return this._OutputDate;
            }
            set
            {
                this._OutputDate = value;
            }
        }

        /// <summary>
        /// OutputFileName
        /// </summary>
        [AttributeField("OutputFileName", "System.String", false, false, false, "String")]
        public string OutputFileName
        {
            get
            {
                return this._OutputFileName;
            }
            set
            {
                this._OutputFileName = value;
            }
        }

        /// <summary>
        /// FilePath
        /// </summary>
        [AttributeField("FilePath", "System.String", false, false, false, "String")]
        public string FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
            }
        }

        /// <summary>
        /// Action
        /// </summary>
        [AttributeField("Action", "System.String", false, false, false, "String")]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this._Action = value;
            }
        }
    }

    /// <summary>
    /// tbl_UnableCard
    /// </summary>
    [Serializable()]
    public class Entity_UnableCardSet : EntitySet<Entity_UnableCard>
    {
    }
}
