//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    /// <summary>
    /// tbl_sletterInfo_CallCust
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_sletterInfo_CallCust")]
    public class Entity_SLetterInfoCallCust : Framework.Data.OM.Entity
    {

        private string _Exp_File;

        /// <summary>
        /// Exp_File
        /// </summary>
        public static string M_Exp_File = "Exp_File";

        private string _Exp_Date;

        /// <summary>
        /// Exp_Date
        /// </summary>
        public static string M_Exp_Date = "Exp_Date";

        private string _ID;

        /// <summary>
        /// ID
        /// </summary>
        public static string M_ID = "ID";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _Source_Flg;

        /// <summary>
        /// Source_Flg
        /// </summary>
        public static string M_Source_Flg = "Source_Flg";

        private string _Maildate;

        /// <summary>
        /// Maildate
        /// </summary>
        public static string M_Maildate = "Maildate";

        private string _Mailno;

        /// <summary>
        /// Mailno
        /// </summary>
        public static string M_Mailno = "Mailno";

        private string _Serial_no;

        /// <summary>
        /// Serial_no
        /// </summary>
        public static string M_Serial_no = "Serial_no";

        private string _Name;

        /// <summary>
        /// Name
        /// </summary>
        public static string M_Name = "Name";

        private string _Htel;

        /// <summary>
        /// Htel
        /// </summary>
        public static string M_Htel = "Htel";

        private string _Otel;

        /// <summary>
        /// Otel
        /// </summary>
        public static string M_Otel = "Otel";

        private string _Dob;

        /// <summary>
        /// Dob
        /// </summary>
        public static string M_Dob = "Dob";

        private string _Zip;

        /// <summary>
        /// Zip
        /// </summary>
        public static string M_Zip = "Zip";

        private string _City;

        /// <summary>
        /// City
        /// </summary>
        public static string M_City = "City";

        private string _Add1;

        /// <summary>
        /// Add1
        /// </summary>
        public static string M_Add1 = "Add1";

        private string _Add2;

        /// <summary>
        /// Add2
        /// </summary>
        public static string M_Add2 = "Add2";

        private string _Add3;

        /// <summary>
        /// Add3
        /// </summary>
        public static string M_Add3 = "Add3";

        private string _Mobil;

        /// <summary>
        /// Mobil
        /// </summary>
        public static string M_Mobil = "Mobil";

        private string _Block_code;

        /// <summary>
        /// Block_code
        /// </summary>
        public static string M_Block_code = "Block_code";

        private string _Ams;

        /// <summary>
        /// Ams
        /// </summary>
        public static string M_Ams = "Ams";

        private string _Imp_File;

        /// <summary>
        /// Imp_File
        /// </summary>
        public static string M_Imp_File = "Imp_File";

        private string _Imp_Date;

        /// <summary>
        /// Imp_Date
        /// </summary>
        public static string M_Imp_Date = "Imp_Date";

        private string _Exp_LetterInfo_File;

        /// <summary>
        /// Exp_LetterInfo_File
        /// </summary>
        public static string M_Exp_LetterInfo_File = "Exp_LetterInfo_File";

        private string _Exp_LetterInfo_Date;

        /// <summary>
        /// Exp_LetterInfo_Date
        /// </summary>
        public static string M_Exp_LetterInfo_Date = "Exp_LetterInfo_Date";

        /// <summary>
        /// Exp_File
        /// </summary>
        [AttributeField("Exp_File", "System.String", false, false, false, "String")]
        public string Exp_File
        {
            get
            {
                return this._Exp_File;
            }
            set
            {
                this._Exp_File = value;
            }
        }

        /// <summary>
        /// Exp_Date
        /// </summary>
        [AttributeField("Exp_Date", "System.String", false, false, false, "String")]
        public string Exp_Date
        {
            get
            {
                return this._Exp_Date;
            }
            set
            {
                this._Exp_Date = value;
            }
        }

        /// <summary>
        /// ID
        /// </summary>
        [AttributeField("ID", "System.String", false, false, false, "String")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this._ID = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// Source_Flg
        /// </summary>
        [AttributeField("Source_Flg", "System.String", false, false, false, "String")]
        public string Source_Flg
        {
            get
            {
                return this._Source_Flg;
            }
            set
            {
                this._Source_Flg = value;
            }
        }

        /// <summary>
        /// Maildate
        /// </summary>
        [AttributeField("Maildate", "System.String", false, false, false, "String")]
        public string Maildate
        {
            get
            {
                return this._Maildate;
            }
            set
            {
                this._Maildate = value;
            }
        }

        /// <summary>
        /// Mailno
        /// </summary>
        [AttributeField("Mailno", "System.String", false, false, false, "String")]
        public string Mailno
        {
            get
            {
                return this._Mailno;
            }
            set
            {
                this._Mailno = value;
            }
        }

        /// <summary>
        /// Serial_no
        /// </summary>
        [AttributeField("Serial_no", "System.String", false, false, false, "String")]
        public string Serial_no
        {
            get
            {
                return this._Serial_no;
            }
            set
            {
                this._Serial_no = value;
            }
        }

        /// <summary>
        /// Name
        /// </summary>
        [AttributeField("Name", "System.String", false, false, false, "String")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this._Name = value;
            }
        }

        /// <summary>
        /// Htel
        /// </summary>
        [AttributeField("Htel", "System.String", false, false, false, "String")]
        public string Htel
        {
            get
            {
                return this._Htel;
            }
            set
            {
                this._Htel = value;
            }
        }

        /// <summary>
        /// Otel
        /// </summary>
        [AttributeField("Otel", "System.String", false, false, false, "String")]
        public string Otel
        {
            get
            {
                return this._Otel;
            }
            set
            {
                this._Otel = value;
            }
        }

        /// <summary>
        /// Dob
        /// </summary>
        [AttributeField("Dob", "System.String", false, false, false, "String")]
        public string Dob
        {
            get
            {
                return this._Dob;
            }
            set
            {
                this._Dob = value;
            }
        }

        /// <summary>
        /// Zip
        /// </summary>
        [AttributeField("Zip", "System.String", false, false, false, "String")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this._Zip = value;
            }
        }

        /// <summary>
        /// City
        /// </summary>
        [AttributeField("City", "System.String", false, false, false, "String")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this._City = value;
            }
        }

        /// <summary>
        /// Add1
        /// </summary>
        [AttributeField("Add1", "System.String", false, false, false, "String")]
        public string Add1
        {
            get
            {
                return this._Add1;
            }
            set
            {
                this._Add1 = value;
            }
        }

        /// <summary>
        /// Add2
        /// </summary>
        [AttributeField("Add2", "System.String", false, false, false, "String")]
        public string Add2
        {
            get
            {
                return this._Add2;
            }
            set
            {
                this._Add2 = value;
            }
        }

        /// <summary>
        /// Add3
        /// </summary>
        [AttributeField("Add3", "System.String", false, false, false, "String")]
        public string Add3
        {
            get
            {
                return this._Add3;
            }
            set
            {
                this._Add3 = value;
            }
        }

        /// <summary>
        /// Mobil
        /// </summary>
        [AttributeField("Mobil", "System.String", false, false, false, "String")]
        public string Mobil
        {
            get
            {
                return this._Mobil;
            }
            set
            {
                this._Mobil = value;
            }
        }

        /// <summary>
        /// Block_code
        /// </summary>
        [AttributeField("Block_code", "System.String", false, false, false, "String")]
        public string Block_code
        {
            get
            {
                return this._Block_code;
            }
            set
            {
                this._Block_code = value;
            }
        }

        /// <summary>
        /// Ams
        /// </summary>
        [AttributeField("Ams", "System.String", false, false, false, "String")]
        public string Ams
        {
            get
            {
                return this._Ams;
            }
            set
            {
                this._Ams = value;
            }
        }

        /// <summary>
        /// Imp_File
        /// </summary>
        [AttributeField("Imp_File", "System.String", false, false, false, "String")]
        public string Imp_File
        {
            get
            {
                return this._Imp_File;
            }
            set
            {
                this._Imp_File = value;
            }
        }

        /// <summary>
        /// Imp_Date
        /// </summary>
        [AttributeField("Imp_Date", "System.String", false, false, false, "String")]
        public string Imp_Date
        {
            get
            {
                return this._Imp_Date;
            }
            set
            {
                this._Imp_Date = value;
            }
        }

        /// <summary>
        /// Exp_LetterInfo_File
        /// </summary>
        [AttributeField("Exp_LetterInfo_File", "System.String", false, false, false, "String")]
        public string Exp_LetterInfo_File
        {
            get
            {
                return this._Exp_LetterInfo_File;
            }
            set
            {
                this._Exp_LetterInfo_File = value;
            }
        }

        /// <summary>
        /// Exp_LetterInfo_Date
        /// </summary>
        [AttributeField("Exp_LetterInfo_Date", "System.String", false, false, false, "String")]
        public string Exp_LetterInfo_Date
        {
            get
            {
                return this._Exp_LetterInfo_Date;
            }
            set
            {
                this._Exp_LetterInfo_Date = value;
            }
        }
    }

    /// <summary>
    /// tbl_sletterInfo_CallCust
    /// </summary>
    [Serializable()]
    public class Entity_SLetterInfoCallCustSet : EntitySet<Entity_SLetterInfoCallCust>
    {
    }

}
