//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_Post_Send_F
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_Post_Send_F")]
    public class EntityM_PostSendF : Framework.Data.OM.Entity
    {
        
        private string _maildate;
        
        /// <summary>
        /// maildate
        /// </summary>
        public static string M_maildate = "maildate";
        
        private string _mailno;
        
        /// <summary>
        /// mailno
        /// </summary>
        public static string M_mailno = "mailno";
        
        private string _F_Type;
        
        /// <summary>
        /// F_Type
        /// </summary>
        public static string M_F_Type = "F_Type";
        
        private string _Info1;
        
        /// <summary>
        /// Info1
        /// </summary>
        public static string M_Info1 = "Info1";
        
        private string _Info2;
        
        /// <summary>
        /// Info2
        /// </summary>
        public static string M_Info2 = "Info2";
        
        private string _Send_status_Code;
        
        /// <summary>
        /// Send_status_Code
        /// </summary>
        public static string M_Send_status_Code = "Send_status_Code";
        
        private string _Send_status_Name;
        
        /// <summary>
        /// Send_status_Name
        /// </summary>
        public static string M_Send_status_Name = "Send_status_Name";
        
        private string _M_date;
        
        /// <summary>
        /// M_date
        /// </summary>
        public static string M_M_date = "M_date";
        
        private string _Post_Code;
        
        /// <summary>
        /// Post_Code
        /// </summary>
        public static string M_Post_Code = "Post_Code";
        
        private string _Post_Name;
        
        /// <summary>
        /// Post_Name
        /// </summary>
        public static string M_Post_Name = "Post_Name";
        
        private string _Post_TEL;
        
        /// <summary>
        /// Post_TEL
        /// </summary>
        public static string M_Post_TEL = "Post_TEL";
        
        private string _Post_ADDR;
        
        /// <summary>
        /// Post_ADDR
        /// </summary>
        public static string M_Post_ADDR = "Post_ADDR";
        
        private string _M_Code;
        
        /// <summary>
        /// M_Code
        /// </summary>
        public static string M_M_Code = "M_Code";
        
        private string _M_Name;
        
        /// <summary>
        /// M_Name
        /// </summary>
        public static string M_M_Name = "M_Name";
        
        private string _Non_Send_Code;
        
        /// <summary>
        /// Non_Send_Code
        /// </summary>
        public static string M_Non_Send_Code = "Non_Send_Code";
        
        private string _Non_Send_Name;
        
        /// <summary>
        /// Non_Send_Name
        /// </summary>
        public static string M_Non_Send_Name = "Non_Send_Name";
        
        private string _Imp_date;
        
        /// <summary>
        /// Imp_date
        /// </summary>
        public static string M_Imp_date = "Imp_date";
        
        private string _Imp_Time;
        
        /// <summary>
        /// Imp_Time
        /// </summary>
        public static string M_Imp_Time = "Imp_Time";
        
        private string _Imp_file;
        
        /// <summary>
        /// Imp_file
        /// </summary>
        public static string M_Imp_file = "Imp_file";
        
        private string _Imp_code;
        
        /// <summary>
        /// Imp_code
        /// </summary>
        public static string M_Imp_code = "Imp_code";
        
        private string _Imp_name;
        
        /// <summary>
        /// Imp_name
        /// </summary>
        public static string M_Imp_name = "Imp_name";
        
        /// <summary>
        /// maildate
        /// </summary>
        [AttributeField("maildate", "System.String", false, true, false, "String")]
        public string maildate
        {
            get
            {
                return this._maildate;
            }
            set
            {
                this._maildate = value;
            }
        }
        
        /// <summary>
        /// mailno
        /// </summary>
        [AttributeField("mailno", "System.String", false, false, false, "String")]
        public string mailno
        {
            get
            {
                return this._mailno;
            }
            set
            {
                this._mailno = value;
            }
        }
        
        /// <summary>
        /// F_Type
        /// </summary>
        [AttributeField("F_Type", "System.String", false, false, false, "String")]
        public string F_Type
        {
            get
            {
                return this._F_Type;
            }
            set
            {
                this._F_Type = value;
            }
        }
        
        /// <summary>
        /// Info1
        /// </summary>
        [AttributeField("Info1", "System.String", false, false, false, "String")]
        public string Info1
        {
            get
            {
                return this._Info1;
            }
            set
            {
                this._Info1 = value;
            }
        }
        
        /// <summary>
        /// Info2
        /// </summary>
        [AttributeField("Info2", "System.String", false, false, false, "String")]
        public string Info2
        {
            get
            {
                return this._Info2;
            }
            set
            {
                this._Info2 = value;
            }
        }
        
        /// <summary>
        /// Send_status_Code
        /// </summary>
        [AttributeField("Send_status_Code", "System.String", false, false, false, "String")]
        public string Send_status_Code
        {
            get
            {
                return this._Send_status_Code;
            }
            set
            {
                this._Send_status_Code = value;
            }
        }
        
        /// <summary>
        /// Send_status_Name
        /// </summary>
        [AttributeField("Send_status_Name", "System.String", false, false, false, "String")]
        public string Send_status_Name
        {
            get
            {
                return this._Send_status_Name;
            }
            set
            {
                this._Send_status_Name = value;
            }
        }
        
        /// <summary>
        /// M_date
        /// </summary>
        [AttributeField("M_date", "System.String", false, false, false, "String")]
        public string M_date
        {
            get
            {
                return this._M_date;
            }
            set
            {
                this._M_date = value;
            }
        }
        
        /// <summary>
        /// Post_Code
        /// </summary>
        [AttributeField("Post_Code", "System.String", false, false, false, "String")]
        public string Post_Code
        {
            get
            {
                return this._Post_Code;
            }
            set
            {
                this._Post_Code = value;
            }
        }
        
        /// <summary>
        /// Post_Name
        /// </summary>
        [AttributeField("Post_Name", "System.String", false, false, false, "String")]
        public string Post_Name
        {
            get
            {
                return this._Post_Name;
            }
            set
            {
                this._Post_Name = value;
            }
        }
        
        /// <summary>
        /// Post_TEL
        /// </summary>
        [AttributeField("Post_TEL", "System.String", false, false, false, "String")]
        public string Post_TEL
        {
            get
            {
                return this._Post_TEL;
            }
            set
            {
                this._Post_TEL = value;
            }
        }
        
        /// <summary>
        /// Post_ADDR
        /// </summary>
        [AttributeField("Post_ADDR", "System.String", false, false, false, "String")]
        public string Post_ADDR
        {
            get
            {
                return this._Post_ADDR;
            }
            set
            {
                this._Post_ADDR = value;
            }
        }
        
        /// <summary>
        /// M_Code
        /// </summary>
        [AttributeField("M_Code", "System.String", false, false, false, "String")]
        public string M_Code
        {
            get
            {
                return this._M_Code;
            }
            set
            {
                this._M_Code = value;
            }
        }
        
        /// <summary>
        /// M_Name
        /// </summary>
        [AttributeField("M_Name", "System.String", false, false, false, "String")]
        public string M_Name
        {
            get
            {
                return this._M_Name;
            }
            set
            {
                this._M_Name = value;
            }
        }
        
        /// <summary>
        /// Non_Send_Code
        /// </summary>
        [AttributeField("Non_Send_Code", "System.String", false, false, false, "String")]
        public string Non_Send_Code
        {
            get
            {
                return this._Non_Send_Code;
            }
            set
            {
                this._Non_Send_Code = value;
            }
        }
        
        /// <summary>
        /// Non_Send_Name
        /// </summary>
        [AttributeField("Non_Send_Name", "System.String", false, false, false, "String")]
        public string Non_Send_Name
        {
            get
            {
                return this._Non_Send_Name;
            }
            set
            {
                this._Non_Send_Name = value;
            }
        }
        
        /// <summary>
        /// Imp_date
        /// </summary>
        [AttributeField("Imp_date", "System.String", false, false, false, "String")]
        public string Imp_date
        {
            get
            {
                return this._Imp_date;
            }
            set
            {
                this._Imp_date = value;
            }
        }
        
        /// <summary>
        /// Imp_Time
        /// </summary>
        [AttributeField("Imp_Time", "System.String", false, false, false, "String")]
        public string Imp_Time
        {
            get
            {
                return this._Imp_Time;
            }
            set
            {
                this._Imp_Time = value;
            }
        }
        
        /// <summary>
        /// Imp_file
        /// </summary>
        [AttributeField("Imp_file", "System.String", false, false, false, "String")]
        public string Imp_file
        {
            get
            {
                return this._Imp_file;
            }
            set
            {
                this._Imp_file = value;
            }
        }
        
        /// <summary>
        /// Imp_code
        /// </summary>
        [AttributeField("Imp_code", "System.String", false, false, false, "String")]
        public string Imp_code
        {
            get
            {
                return this._Imp_code;
            }
            set
            {
                this._Imp_code = value;
            }
        }
        
        /// <summary>
        /// Imp_name
        /// </summary>
        [AttributeField("Imp_name", "System.String", false, false, false, "String")]
        public string Imp_name
        {
            get
            {
                return this._Imp_name;
            }
            set
            {
                this._Imp_name = value;
            }
        }
    }
    
    /// <summary>
    /// tbl_Post_Send_F
    /// </summary>
    [Serializable()]
    public class EntityM_PostSendFSet : EntitySet<EntityM_PostSendF>
    {
    }
}
