//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{


    /// <summary>
    /// tbl_CancelOASA_FileName
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_CancelOASA_FileName")]
    public class Entity_CancelOASA_FileName : Framework.Data.OM.Entity
    {

        private string _CancelOASADate;

        /// <summary>
        /// CancelOASADate
        /// </summary>
        public static string M_CancelOASADate = "CancelOASADate";

        private string _CancelOASAFile;

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        public static string M_CancelOASAFile = "CancelOASAFile";

        /// <summary>
        /// CancelOASADate
        /// </summary>
        [AttributeField("CancelOASADate", "System.String", false, false, false, "String")]
        public string CancelOASADate
        {
            get
            {
                return this._CancelOASADate;
            }
            set
            {
                this._CancelOASADate = value;
            }
        }

        /// <summary>
        /// CancelOASAFile
        /// </summary>
        [AttributeField("CancelOASAFile", "System.String", false, false, false, "String")]
        public string CancelOASAFile
        {
            get
            {
                return this._CancelOASAFile;
            }
            set
            {
                this._CancelOASAFile = value;
            }
        }
    }

    /// <summary>
    /// tbl_CancelOASA_FileName
    /// </summary>
    [Serializable()]
    public class Entity_CancelOASA_FileNameSet : EntitySet<Entity_CancelOASA_FileName>
    {
    }
}
