//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_Card_BackInfo
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_Card_BackInfo")]
    public class Entity_CardBackInfo : Framework.Data.OM.Entity
    {

        private string _serial_no;

        /// <summary>
        /// serial_no
        /// </summary>
        public static string M_serial_no = "serial_no";

        private string _CardNo;

        /// <summary>
        /// CardNo
        /// </summary>
        public static string M_CardNo = "CardNo";

        private string _Action;

        /// <summary>
        /// Action
        /// </summary>
        public static string M_Action = "Action";

        private string _Id;

        /// <summary>
        /// Id
        /// </summary>
        public static string M_Id = "Id";

        private string _CustName;

        /// <summary>
        /// CustName
        /// </summary>
        public static string M_CustName = "CustName";

        private string _Trandate;

        /// <summary>
        /// Trandate
        /// </summary>
        public static string M_Trandate = "Trandate";

        private string _cardtype;

        /// <summary>
        /// cardtype
        /// </summary>
        public static string M_cardtype = "cardtype";

        private string _Kind;

        /// <summary>
        /// Kind
        /// </summary>
        public static string M_Kind = "Kind";

        private string _Reason;

        /// <summary>
        /// Reason
        /// </summary>
        public static string M_Reason = "Reason";

        private string _Backdate;

        /// <summary>
        /// Backdate
        /// </summary>
        public static string M_Backdate = "Backdate";

        private string _Madd1;

        /// <summary>
        /// Madd1
        /// </summary>
        public static string M_Madd1 = "Madd1";

        private string _Madd2;

        /// <summary>
        /// Madd2
        /// </summary>
        public static string M_Madd2 = "Madd2";

        private string _Madd3;

        /// <summary>
        /// Madd3
        /// </summary>
        public static string M_Madd3 = "Madd3";

        private string _OldZip;

        /// <summary>
        /// OldZip
        /// </summary>
        public static string M_OldZip = "OldZip";

        private string _OldAdd1;

        /// <summary>
        /// OldAdd1
        /// </summary>
        public static string M_OldAdd1 = "OldAdd1";

        private string _OldAdd2;

        /// <summary>
        /// OldAdd2
        /// </summary>
        public static string M_OldAdd2 = "OldAdd2";

        private string _OldAdd3;

        /// <summary>
        /// OldAdd3
        /// </summary>
        public static string M_OldAdd3 = "OldAdd3";

        private string _NewName;

        /// <summary>
        /// NewName
        /// </summary>
        public static string M_NewName = "NewName";

        private string _NewZip;

        /// <summary>
        /// NewZip
        /// </summary>
        public static string M_NewZip = "NewZip";

        private string _NewAdd1;

        /// <summary>
        /// NewAdd1
        /// </summary>
        public static string M_NewAdd1 = "NewAdd1";

        private string _NewAdd2;

        /// <summary>
        /// NewAdd2
        /// </summary>
        public static string M_NewAdd2 = "NewAdd2";

        private string _NewAdd3;

        /// <summary>
        /// NewAdd3
        /// </summary>
        public static string M_NewAdd3 = "NewAdd3";

        private string _ImportDate;

        /// <summary>
        /// ImportDate
        /// </summary>
        public static string M_ImportDate = "ImportDate";

        private string _ImportFileName;

        /// <summary>
        /// ImportFileName
        /// </summary>
        public static string M_ImportFileName = "ImportFileName";

        private string _Enditem;

        /// <summary>
        /// Enditem
        /// </summary>
        public static string M_Enditem = "Enditem";

        private string _Enddate;

        /// <summary>
        /// Enddate
        /// </summary>
        public static string M_Enddate = "Enddate";

        private string _Enduid;

        /// <summary>
        /// Enduid
        /// </summary>
        public static string M_Enduid = "Enduid";

        private string _Endnote;

        /// <summary>
        /// Endnote
        /// </summary>
        public static string M_Endnote = "Endnote";

        private string _EndFunction;

        /// <summary>
        /// EndFunction
        /// </summary>
        public static string M_EndFunction = "EndFunction";

        private string _Closedate;

        /// <summary>
        /// Closedate
        /// </summary>
        public static string M_Closedate = "Closedate";

        private string _CardBackStatus;

        /// <summary>
        /// CardBackStatus
        /// </summary>
        public static string M_CardBackStatus = "CardBackStatus";

        private string _Maildate;

        /// <summary>
        /// Maildate
        /// </summary>
        public static string M_Maildate = "Maildate";

        private string _Mailno;

        /// <summary>
        /// Mailno
        /// </summary>
        public static string M_Mailno = "Mailno";

        private string _InformMerchDate;

        /// <summary>
        /// InformMerchDate
        /// </summary>
        public static string M_InformMerchDate = "InformMerchDate";

        private string _Blockcode;

        /// <summary>
        /// Blockcode
        /// </summary>
        public static string M_Blockcode = "Blockcode";

        private string _Exp_Count;

        /// <summary>
        /// Exp_Count
        /// </summary>
        public static string M_Exp_Count = "Exp_Count";

        private string _Exp_Date;

        /// <summary>
        /// Exp_Date
        /// </summary>
        public static string M_Exp_Date = "Exp_Date";

        private string _OriginalDBflg;

        /// <summary>
        /// OriginalDBflg
        /// </summary>
        public static string M_OriginalDBflg = "OriginalDBflg";

        private string _Endtime;

        /// <summary>
        /// Endtime
        /// </summary>
        public static string M_Endtime = "Endtime";

        /// <summary>
        /// serial_no
        /// </summary>
        [AttributeField("serial_no", "System.String", false, true, false, "String")]
        public string serial_no
        {
            get
            {
                return this._serial_no;
            }
            set
            {
                this._serial_no = value;
            }
        }

        /// <summary>
        /// CardNo
        /// </summary>
        [AttributeField("CardNo", "System.String", false, false, false, "String")]
        public string CardNo
        {
            get
            {
                return this._CardNo;
            }
            set
            {
                this._CardNo = value;
            }
        }

        /// <summary>
        /// Action
        /// </summary>
        [AttributeField("Action", "System.String", false, false, false, "String")]
        public string Action
        {
            get
            {
                return this._Action;
            }
            set
            {
                this._Action = value;
            }
        }

        /// <summary>
        /// Id
        /// </summary>
        [AttributeField("Id", "System.String", false, false, false, "String")]
        public string Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

        /// <summary>
        /// CustName
        /// </summary>
        [AttributeField("CustName", "System.String", false, false, false, "String")]
        public string CustName
        {
            get
            {
                return this._CustName;
            }
            set
            {
                this._CustName = value;
            }
        }

        /// <summary>
        /// Trandate
        /// </summary>
        [AttributeField("Trandate", "System.String", false, false, false, "String")]
        public string Trandate
        {
            get
            {
                return this._Trandate;
            }
            set
            {
                this._Trandate = value;
            }
        }

        /// <summary>
        /// cardtype
        /// </summary>
        [AttributeField("cardtype", "System.String", false, false, false, "String")]
        public string cardtype
        {
            get
            {
                return this._cardtype;
            }
            set
            {
                this._cardtype = value;
            }
        }

        /// <summary>
        /// Kind
        /// </summary>
        [AttributeField("Kind", "System.String", false, false, false, "String")]
        public string Kind
        {
            get
            {
                return this._Kind;
            }
            set
            {
                this._Kind = value;
            }
        }

        /// <summary>
        /// Reason
        /// </summary>
        [AttributeField("Reason", "System.String", false, false, false, "String")]
        public string Reason
        {
            get
            {
                return this._Reason;
            }
            set
            {
                this._Reason = value;
            }
        }

        /// <summary>
        /// Backdate
        /// </summary>
        [AttributeField("Backdate", "System.String", false, false, false, "String")]
        public string Backdate
        {
            get
            {
                return this._Backdate;
            }
            set
            {
                this._Backdate = value;
            }
        }

        /// <summary>
        /// Madd1
        /// </summary>
        [AttributeField("Madd1", "System.String", false, false, false, "String")]
        public string Madd1
        {
            get
            {
                return this._Madd1;
            }
            set
            {
                this._Madd1 = value;
            }
        }

        /// <summary>
        /// Madd2
        /// </summary>
        [AttributeField("Madd2", "System.String", false, false, false, "String")]
        public string Madd2
        {
            get
            {
                return this._Madd2;
            }
            set
            {
                this._Madd2 = value;
            }
        }

        /// <summary>
        /// Madd3
        /// </summary>
        [AttributeField("Madd3", "System.String", false, false, false, "String")]
        public string Madd3
        {
            get
            {
                return this._Madd3;
            }
            set
            {
                this._Madd3 = value;
            }
        }

        /// <summary>
        /// OldZip
        /// </summary>
        [AttributeField("OldZip", "System.String", false, false, false, "String")]
        public string OldZip
        {
            get
            {
                return this._OldZip;
            }
            set
            {
                this._OldZip = value;
            }
        }

        /// <summary>
        /// OldAdd1
        /// </summary>
        [AttributeField("OldAdd1", "System.String", false, false, false, "String")]
        public string OldAdd1
        {
            get
            {
                return this._OldAdd1;
            }
            set
            {
                this._OldAdd1 = value;
            }
        }

        /// <summary>
        /// OldAdd2
        /// </summary>
        [AttributeField("OldAdd2", "System.String", false, false, false, "String")]
        public string OldAdd2
        {
            get
            {
                return this._OldAdd2;
            }
            set
            {
                this._OldAdd2 = value;
            }
        }

        /// <summary>
        /// OldAdd3
        /// </summary>
        [AttributeField("OldAdd3", "System.String", false, false, false, "String")]
        public string OldAdd3
        {
            get
            {
                return this._OldAdd3;
            }
            set
            {
                this._OldAdd3 = value;
            }
        }

        /// <summary>
        /// NewName
        /// </summary>
        [AttributeField("NewName", "System.String", false, false, false, "String")]
        public string NewName
        {
            get
            {
                return this._NewName;
            }
            set
            {
                this._NewName = value;
            }
        }

        /// <summary>
        /// NewZip
        /// </summary>
        [AttributeField("NewZip", "System.String", false, false, false, "String")]
        public string NewZip
        {
            get
            {
                return this._NewZip;
            }
            set
            {
                this._NewZip = value;
            }
        }

        /// <summary>
        /// NewAdd1
        /// </summary>
        [AttributeField("NewAdd1", "System.String", false, false, false, "String")]
        public string NewAdd1
        {
            get
            {
                return this._NewAdd1;
            }
            set
            {
                this._NewAdd1 = value;
            }
        }

        /// <summary>
        /// NewAdd2
        /// </summary>
        [AttributeField("NewAdd2", "System.String", false, false, false, "String")]
        public string NewAdd2
        {
            get
            {
                return this._NewAdd2;
            }
            set
            {
                this._NewAdd2 = value;
            }
        }

        /// <summary>
        /// NewAdd3
        /// </summary>
        [AttributeField("NewAdd3", "System.String", false, false, false, "String")]
        public string NewAdd3
        {
            get
            {
                return this._NewAdd3;
            }
            set
            {
                this._NewAdd3 = value;
            }
        }

        /// <summary>
        /// ImportDate
        /// </summary>
        [AttributeField("ImportDate", "System.String", false, false, false, "String")]
        public string ImportDate
        {
            get
            {
                return this._ImportDate;
            }
            set
            {
                this._ImportDate = value;
            }
        }

        /// <summary>
        /// ImportFileName
        /// </summary>
        [AttributeField("ImportFileName", "System.String", false, false, false, "String")]
        public string ImportFileName
        {
            get
            {
                return this._ImportFileName;
            }
            set
            {
                this._ImportFileName = value;
            }
        }

        /// <summary>
        /// Enditem
        /// </summary>
        [AttributeField("Enditem", "System.String", false, false, false, "String")]
        public string Enditem
        {
            get
            {
                return this._Enditem;
            }
            set
            {
                this._Enditem = value;
            }
        }

        /// <summary>
        /// Enddate
        /// </summary>
        [AttributeField("Enddate", "System.String", false, false, false, "String")]
        public string Enddate
        {
            get
            {
                return this._Enddate;
            }
            set
            {
                this._Enddate = value;
            }
        }

        /// <summary>
        /// Enduid
        /// </summary>
        [AttributeField("Enduid", "System.String", false, false, false, "String")]
        public string Enduid
        {
            get
            {
                return this._Enduid;
            }
            set
            {
                this._Enduid = value;
            }
        }

        /// <summary>
        /// Endnote
        /// </summary>
        [AttributeField("Endnote", "System.String", false, false, false, "String")]
        public string Endnote
        {
            get
            {
                return this._Endnote;
            }
            set
            {
                this._Endnote = value;
            }
        }

        /// <summary>
        /// EndFunction
        /// </summary>
        [AttributeField("EndFunction", "System.String", false, false, false, "String")]
        public string EndFunction
        {
            get
            {
                return this._EndFunction;
            }
            set
            {
                this._EndFunction = value;
            }
        }

        /// <summary>
        /// Closedate
        /// </summary>
        [AttributeField("Closedate", "System.String", false, false, false, "String")]
        public string Closedate
        {
            get
            {
                return this._Closedate;
            }
            set
            {
                this._Closedate = value;
            }
        }

        /// <summary>
        /// CardBackStatus
        /// </summary>
        [AttributeField("CardBackStatus", "System.String", false, false, false, "String")]
        public string CardBackStatus
        {
            get
            {
                return this._CardBackStatus;
            }
            set
            {
                this._CardBackStatus = value;
            }
        }

        /// <summary>
        /// Maildate
        /// </summary>
        [AttributeField("Maildate", "System.String", false, false, false, "String")]
        public string Maildate
        {
            get
            {
                return this._Maildate;
            }
            set
            {
                this._Maildate = value;
            }
        }

        /// <summary>
        /// Mailno
        /// </summary>
        [AttributeField("Mailno", "System.String", false, false, false, "String")]
        public string Mailno
        {
            get
            {
                return this._Mailno;
            }
            set
            {
                this._Mailno = value;
            }
        }

        /// <summary>
        /// InformMerchDate
        /// </summary>
        [AttributeField("InformMerchDate", "System.String", false, false, false, "String")]
        public string InformMerchDate
        {
            get
            {
                return this._InformMerchDate;
            }
            set
            {
                this._InformMerchDate = value;
            }
        }

        /// <summary>
        /// Blockcode
        /// </summary>
        [AttributeField("Blockcode", "System.String", false, false, false, "String")]
        public string Blockcode
        {
            get
            {
                return this._Blockcode;
            }
            set
            {
                this._Blockcode = value;
            }
        }

        /// <summary>
        /// Exp_Count
        /// </summary>
        [AttributeField("Exp_Count", "System.String", false, false, false, "String")]
        public string Exp_Count
        {
            get
            {
                return this._Exp_Count;
            }
            set
            {
                this._Exp_Count = value;
            }
        }

        /// <summary>
        /// Exp_Date
        /// </summary>
        [AttributeField("Exp_Date", "System.String", false, false, false, "String")]
        public string Exp_Date
        {
            get
            {
                return this._Exp_Date;
            }
            set
            {
                this._Exp_Date = value;
            }
        }

        /// <summary>
        /// OriginalDBflg
        /// </summary>
        [AttributeField("OriginalDBflg", "System.String", false, false, false, "String")]
        public string OriginalDBflg
        {
            get
            {
                return this._OriginalDBflg;
            }
            set
            {
                this._OriginalDBflg = value;
            }
        }

        /// <summary>
        /// Endtime
        /// </summary>
        [AttributeField("Endtime", "System.String", false, false, false, "String")]
        public string Endtime
        {
            get
            {
                return this._Endtime;
            }
            set
            {
                this._Endtime = value;
            }
        }
    }
    
    /// <summary>
    /// tbl_Card_BackInfo
    /// </summary>
    [Serializable()]
    public class Entity_CardBackInfoSet : EntitySet<Entity_CardBackInfo>
    {
    }
}
