//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.42
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Framework.Data.OM.OMAttribute;
using Framework.Data.OM;
using Framework.Data.OM.Collections;


namespace EntityLayer
{
    
    
    /// <summary>
    /// tbl_Card_ StockInfo
    /// </summary>
    [Serializable()]
    [AttributeTable("tbl_Card_StockInfo")]
    public class Entity_CardStockInfo : Framework.Data.OM.Entity
    {

        private string _IntoStore_Date;

        /// <summary>
        /// IntoStore_Date
        /// </summary>
        public static string M_IntoStore_Date = "IntoStore_Date";

        private string _cardno;

        /// <summary>
        /// cardno
        /// </summary>
        public static string M_cardno = "cardno";

        private string _OutStore_Status;

        /// <summary>
        /// OutStore_Status
        /// </summary>
        public static string M_OutStore_Status = "OutStore_Status";

        private string _OutStore_Date;

        /// <summary>
        /// OutStore_Date
        /// </summary>
        public static string M_OutStore_Date = "OutStore_Date";

        private string _custname;

        /// <summary>
        /// custname
        /// </summary>
        public static string M_custname = "custname";

        private string _id;

        /// <summary>
        /// id
        /// </summary>
        public static string M_id = "id";

        private string _action;

        /// <summary>
        /// action
        /// </summary>
        public static string M_action = "action";

        private string _trandate;

        /// <summary>
        /// trandate
        /// </summary>
        public static string M_trandate = "trandate";

        private string _mailno;

        /// <summary>
        /// mailno
        /// </summary>
        public static string M_mailno = "mailno";

        /// <summary>
        /// IntoStore_Date
        /// </summary>
        [AttributeField("IntoStore_Date", "System.String", false, true, false, "String")]
        public string IntoStore_Date
        {
            get
            {
                return this._IntoStore_Date;
            }
            set
            {
                this._IntoStore_Date = value;
            }
        }

        /// <summary>
        /// cardno
        /// </summary>
        [AttributeField("cardno", "System.String", false, true, false, "String")]
        public string cardno
        {
            get
            {
                return this._cardno;
            }
            set
            {
                this._cardno = value;
            }
        }

        /// <summary>
        /// OutStore_Status
        /// </summary>
        [AttributeField("OutStore_Status", "System.String", false, false, false, "String")]
        public string OutStore_Status
        {
            get
            {
                return this._OutStore_Status;
            }
            set
            {
                this._OutStore_Status = value;
            }
        }

        /// <summary>
        /// OutStore_Date
        /// </summary>
        [AttributeField("OutStore_Date", "System.String", false, false, false, "String")]
        public string OutStore_Date
        {
            get
            {
                return this._OutStore_Date;
            }
            set
            {
                this._OutStore_Date = value;
            }
        }

        /// <summary>
        /// custname
        /// </summary>
        [AttributeField("custname", "System.String", false, false, false, "String")]
        public string custname
        {
            get
            {
                return this._custname;
            }
            set
            {
                this._custname = value;
            }
        }

        /// <summary>
        /// id
        /// </summary>
        [AttributeField("id", "System.String", false, false, false, "String")]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
            }
        }

        /// <summary>
        /// action
        /// </summary>
        [AttributeField("action", "System.String", false, false, false, "String")]
        public string action
        {
            get
            {
                return this._action;
            }
            set
            {
                this._action = value;
            }
        }

        /// <summary>
        /// trandate
        /// </summary>
        [AttributeField("trandate", "System.String", false, false, false, "String")]
        public string trandate
        {
            get
            {
                return this._trandate;
            }
            set
            {
                this._trandate = value;
            }
        }

        /// <summary>
        /// mailno
        /// </summary>
        [AttributeField("mailno", "System.String", false, false, false, "String")]
        public string mailno
        {
            get
            {
                return this._mailno;
            }
            set
            {
                this._mailno = value;
            }
        }

    }
    
    /// <summary>
    /// tbl_Card_ StockInfo
    /// </summary>
    [Serializable()]
    public class Entity_CardStockInfoSet : EntitySet<Entity_CardStockInfo>
    {
    }
}
